CREATE TABLE `daily_short_signals` (
  `id` integer PRIMARY KEY AUTO_INCREMENT,
  `ts_code` varchar(255) NOT NULL COMMENT 'TS代码',
  `trade_date` date NOT NULL COMMENT '交易日期',
  `ma20_down` tinyint(2) COMMENT 'MA20下行',
  `ema20_down` tinyint(2) COMMENT 'EMA20下行',
  `ma30_down` tinyint(2) COMMENT 'MA30下行',
  `ema30_down` tinyint(2) COMMENT 'EMA30下行',
  `ma60_down` tinyint(2) COMMENT 'MA60下行',
  `ema60_down` tinyint(2) COMMENT 'EMA60下行',
  `ma120_down` tinyint(2) COMMENT 'MA120下行',
  `ema120_down` tinyint(2) COMMENT 'EMA120下行',
  `ma_arrange` tinyint(2) COMMENT 'MA空头排列（5/10/20/60）',
  `ema_arrange` tinyint(2) COMMENT 'EMA空头排列（5/10/20/60）',
  `short_ma_arrange1` tinyint(2) COMMENT 'MA短期组合空头排列（5/10/20）',
  `short_ma_arrange2` tinyint(2) COMMENT 'MA短期组合空头排列（5/10/30）',
  `short_ema_arrange1` tinyint(2) COMMENT 'EMA短期组合空头排列（5/10/20）',
  `short_ema_arrange2` tinyint(2) COMMENT 'EMA短期组合空头排列（5/10/30）',
  `middle_ma_arrange1` tinyint(2) COMMENT 'MA中期组合空头排列（10/20/60）',
  `middle_ma_arrange2` tinyint(2) COMMENT 'MA中期组合空头排列（10/20/55）',
  `middle_ema_arrange1` tinyint(2) COMMENT 'EMA中期组合空头排列（10/20/60）',
  `middle_ema_arrange2` tinyint(2) COMMENT 'EMA中期组合空头排列（10/20/55）',
  `long_ma_arrange1` tinyint(2) COMMENT 'MA长期组合空头排列（20/55/120）',
  `long_ma_arrange2` tinyint(2) COMMENT 'MA长期组合空头排列（30/60/120）',
  `long_ema_arrange1` tinyint(2) COMMENT 'EMA长期组合空头排列（20/55/120）',
  `long_ema_arrange2` tinyint(2) COMMENT 'EMA长期组合空头排列（30/60/120）',
  `ma_dead_cross1` tinyint(2) COMMENT 'MA死亡交叉（5/10）',
  `ma_dead_cross2` tinyint(2) COMMENT 'MA死亡交叉（5/20）',
  `ma_dead_cross3` tinyint(2) COMMENT 'MA死亡交叉（10/20）',
  `ma_dead_cross4` tinyint(2) COMMENT 'MA死亡交叉（10/30）',
  `ema_dead_cross1` tinyint(2) COMMENT 'EMA死亡交叉（5/10）',
  `ema_dead_cross2` tinyint(2) COMMENT 'EMA死亡交叉（5/20）',
  `ema_dead_cross3` tinyint(2) COMMENT 'EMA死亡交叉（10/20）',
  `ema_dead_cross4` tinyint(2) COMMENT 'EMA死亡交叉（10/30）',
  `ma_dead_valley` tinyint(2) COMMENT 'MA死亡谷（5/10，5/20，10/20）',
  `ema_dead_valley` tinyint(2) COMMENT 'EMA死亡谷（5/10，5/20，10/20）',
  `ma_knife` tinyint(2) COMMENT 'MA断头铡刀(5/10/20)',
  `ema_knife` tinyint(2) COMMENT 'EMA断头铡刀(5/10/20)',
  `ma_dark_cloud` tinyint(2) COMMENT 'MA乌云密布(5/10/20)',
  `ema_dark_cloud` tinyint(2) COMMENT 'EMA乌云密布(5/10/20)',
  `ma_set_sail` tinyint(2) COMMENT 'MA战机起航(5/10/20)',
  `ema_set_sail` tinyint(2) COMMENT 'EMA战机起航(5/10/20)',
  `ma_supreme` tinyint(2) COMMENT 'MA气贯长虹(5/10/20)',
  `ema_supreme` tinyint(2) COMMENT 'EMA气贯长虹(5/10/20)',
  `ma_dead_jump` tinyint(2) COMMENT 'MA绝命跳(5/10/20)',
  `ema_dead_jump` tinyint(2) COMMENT 'EMA绝命跳(5/10/20)',
  `ma_spider` tinyint(2) COMMENT 'MA毒蜘蛛(5/10/20)',
  `ma_spider2` tinyint(2) COMMENT 'MA毒蜘蛛(5/10/20/30)',
  `ema_spider` tinyint(2) COMMENT 'EMA毒蜘蛛(5/10/20)',
  `ema_spider2` tinyint(2) COMMENT 'EMA毒蜘蛛(5/10/20/30)',
  `td8` tinyint(2),
  `td9` tinyint(2),
  `bias6` tinyint(2),
  `bias12` tinyint(2),
  `bias24` tinyint(2),
  `bias60` tinyint(2),
  `bias72` tinyint(2),
  `bias120` tinyint(2),
  `long_end` tinyint(1) COMMENT '尽头线(short)',
  `swallow_down` tinyint(1) COMMENT '看跌吞没(short)',
  `hang_neck` tinyint(1) COMMENT '吊颈线(short)',
  `shooting` tinyint(1) COMMENT '射击之星(short)',
  `jump_line` tinyint(1) COMMENT '跌停一字线(short)',
  `up_screw` tinyint(1) COMMENT '上涨螺旋桨(short)'
);

CREATE INDEX `daily_short_signals_index_ts_code` ON `daily_short_signals` (`ts_code`);
CREATE INDEX `daily_short_signals_index_trade_date` ON `daily_short_signals` (`trade_date`);
CREATE UNIQUE INDEX `daily_short_signals_unique` ON `daily_short_signals` (`ts_code`, `trade_date`);
