CREATE TABLE `daily_indicators` (
  `id` integer PRIMARY KEY AUTO_INCREMENT,
  `ts_code` varchar(255) NOT NULL COMMENT 'TS代码',
  `trade_date` date NOT NULL COMMENT '交易日期',
  `ma5` float,
  `ma10` float,
  `ma20` float,
  `ma30` float,
  `ma34` float,
  `ma55` float,
  `ma60` float,
  `ma120` float,
  `ma144` float,
  `ma169` float,
  `ema5` float,
  `ema10` float,
  `ema20` float,
  `ema30` float,
  `ema34` float,
  `ema55` float,
  `ema60` float,
  `ema120` float,
  `ema144` float,
  `ema169` float,
  `ema288` float,
  `ema338` float,
  `ema576` float,
  `ema676` float,
  `ma5_slope` float,
  `ma10_slope` float,
  `ma20_slope` float,
  `ma30_slope` float,
  `ma34_slope` float,
  `ma55_slope` float,
  `ma60_slope` float,
  `ma120_slope` float,
  `ma144_slope` float,
  `ma169_slope` float,
  `ema5_slope` float,
  `ema10_slope` float,
  `ema20_slope` float,
  `ema30_slope` float,
  `ema34_slope` float,
  `ema55_slope` float,
  `ema60_slope` float,
  `ema120_slope` float,
  `ema144_slope` float,
  `ema169_slope` float,
  `ema288_slope` float,
  `ema338_slope` float,
  `ema576_slope` float,
  `ema676_slope` float,
  `diff` float,
  `dea` float,
  `macd` float,
  `bias6` float,
  `bias12` float,
  `bias24` float,
  `bias60` float,
  `bias72` float,
  `bias120` float,
  `high_td` tinyint(2),
  `low_td` tinyint(2)
);

CREATE INDEX `daily_indicators_index_ts_code` ON `daily_indicators` (`ts_code`);
CREATE INDEX `daily_indicators_index_trade_date` ON `daily_indicators` (`trade_date`);
CREATE UNIQUE INDEX `daily_indicators_unique` ON `daily_indicators` (`ts_code`, `trade_date`);
