CREATE TABLE `daily_pattern_signals` (
  `id` integer PRIMARY KEY AUTO_INCREMENT,
  `ts_code` varchar(255) NOT NULL COMMENT 'TS代码',
  `exchange` varchar(255) NOT NULL COMMENT '交易所代码 SSE SZSE HK US',
  `trade_date` date NOT NULL COMMENT '交易日期',
  `CDLCLOSINGMARUBOZU` tinyint(3) COMMENT '收盘缺影线-持续 一日K',
  `CDLDOJI` tinyint(3) COMMENT '十字',
  `CDLDOJISTAR` tinyint(3) COMMENT '十字星 反转',
  `CDLDRAGONFLYDOJI` tinyint(3) COMMENT '蜻蜓十字/T形十字 反转',
  `CDLGRAVESTONEDOJI` tinyint(3) COMMENT '墓碑十字/倒T十字 底部反转',
  `CDLHAMMER` tinyint(3) COMMENT '锤头 底部反转',
  `CDLHANGINGMAN` tinyint(3) COMMENT '上吊线 顶部反转',
  `CDLLONGLEGGEDDOJI` tinyint(3) COMMENT '长脚十字',
  `CDLLONGLINE` tinyint(3) COMMENT '长蜡烛',
  `CDLMARUBOZU` tinyint(3) COMMENT '光头光脚/缺影线',
  `CDLRICKSHAWMAN` tinyint(3) COMMENT '黄包车夫',
  `CDLSHOOTINGSTAR` tinyint(3) COMMENT '射击之星 看跌',
  `CDLSHORTLINE` tinyint(3) COMMENT '短蜡烛',
  `CDLTAKURI` tinyint(3) COMMENT '探水竿',
  `CDLCOUNTERATTACK` tinyint(3) COMMENT '反击线 两日K',
  `CDLDARKCLOUDCOVER` tinyint(3) COMMENT '乌云压顶 看跌 两日K',
  `CDLGAPSIDESIDEWHITE` tinyint(3) COMMENT '向上/下跳空并列阳线 两日K',
  `CDLHARAMI` tinyint(3) COMMENT '孕线 反转 两日K',
  `CDLHARAMICROSS` tinyint(3) COMMENT '十字孕线 反转 两日K',
  `CDLHOMINGPIGEON` tinyint(3) COMMENT '家鸽 两日K',
  `CDLINNECK` tinyint(3) COMMENT '颈内线 两日K',
  `CDLKICKING` tinyint(3) COMMENT '反冲形态 两日K',
  `CDLKICKINGBYLENGTH` tinyint(3) COMMENT '由较长缺影线决定的反冲形态 两日K',
  `CDLMATCHINGLOW` tinyint(3) COMMENT '相同低价 两日K',
  `CDLONNECK` tinyint(3) COMMENT '颈上线 两日K',
  `CDLSEPARATINGLINES` tinyint(3) COMMENT '分离线 两日K',
  `CDLTHRUSTING` tinyint(3) COMMENT '插入 两日K',
  `CDLBELTHOLD` tinyint(3) COMMENT '捉腰带线 两日K',
  `CDLENGULFING` tinyint(3) COMMENT '吞噬模式 两日K',
  `CDLPIERCING` tinyint(3) COMMENT '刺透形态 两日K',
  `CDL2CROWS` tinyint(3) COMMENT '两只乌鸦 三日K',
  `CDL3BLACKCROWS` tinyint(3) COMMENT '三只乌鸦 三日K',
  `CDL3INSIDE` tinyint(3) COMMENT '三内部上涨和下跌 三日K',
  `CDL3OUTSIDE` tinyint(3) COMMENT '三外部上涨和下跌 三日K',
  `CDL3STARSINSOUTH` tinyint(3) COMMENT '南方三星 三日K',
  `CDLABANDONEDBABY` tinyint(3) COMMENT '弃婴 三日K',
  `CDLUNIQUE3RIVER` tinyint(3) COMMENT '奇特三川 三日K',
  `CDLMORNINGSTAR` tinyint(3) COMMENT '早晨之星 三日K',
  `CDLMORNINGDOJISTAR` tinyint(3) COMMENT '早晨十字星 三日K',
  `CDLEVENINGSTAR` tinyint(3) COMMENT '黄昏之星 三日K',
  `CDLEVENINGDOJISTAR` tinyint(3) COMMENT '黄昏十字星 三日K',
  `CDL3WHITESOLDIERS` tinyint(3) COMMENT '三个白兵 三日K',
  `CDLADVANCEBLOCK` tinyint(3) COMMENT '大敌当前 三日K',
  `CDLHIGHWAVE` tinyint(3) COMMENT '风高浪大线 三日K',
  `CDLHIKKAKE` tinyint(3) COMMENT '陷阱 三日K',
  `CDLHIKKAKEMOD` tinyint(3) COMMENT '修正陷阱 三日K',
  `CDLIDENTICAL3CROWS` tinyint(3) COMMENT '三胞胎乌鸦 三日K',
  `CDLSPINNINGTOP` tinyint(3) COMMENT '纺锤 三日K',
  `CDLSTALLEDPATTERN` tinyint(3) COMMENT '停顿形态 三日K',
  `CDLSTICKSANDWICH` tinyint(3) COMMENT '条形三明治 三日K',
  `CDLTASUKIGAP` tinyint(3) COMMENT '跳空并列阴阳线 三日K',
  `CDLTRISTAR` tinyint(3) COMMENT '三星 三日K',
  `CDLUPSIDEGAP2CROWS` tinyint(3) COMMENT '向上跳空的两只乌鸦 三日K',
  `CDL3LINESTRIKE` tinyint(3) COMMENT '三线打击 四日K',
  `CDLCONCEALBABYSWALL` tinyint(3) COMMENT '藏婴吞没 底部反转 四日K',
  `CDLBREAKAWAY` tinyint(3) COMMENT '脱离 五日K',
  `CDLLADDERBOTTOM` tinyint(3) COMMENT '梯底 五日K',
  `CDLMATHOLD` tinyint(3) COMMENT '铺垫 五日K',
  `CDLRISEFALL3METHODS` tinyint(3) COMMENT '上升/下降三法 五日K',
  `CDLXSIDEGAP3METHODS` tinyint(3) COMMENT '上升/下降跳空三法 五日K'
);

CREATE INDEX `daily_pattern_signals_index_exchange` ON `daily_pattern_signals` (`exchange`);
CREATE INDEX `daily_pattern_signals_index_ts_code` ON `daily_pattern_signals` (`ts_code`);
CREATE INDEX `daily_pattern_signals_index_trade_date` ON `daily_pattern_signals` (`trade_date`);
CREATE UNIQUE INDEX `daily_pattern_signals_unique` ON `daily_pattern_signals` (`ts_code`, `trade_date`);