CREATE TABLE `daily_pattern_signals` (
  `id` integer PRIMARY KEY AUTO_INCREMENT,
  `ts_code` varchar(255) NOT NULL COMMENT 'TS代码',
  `exchange` varchar(255) NOT NULL COMMENT '交易所代码 SSE SZSE HK US',
  `trade_date` date NOT NULL COMMENT '交易日期',
  `CDLCLOSINGMARUBOZU` smallint(5) COMMENT '收盘缺影线-持续 一日K',
  `CDLDOJI` smallint(5) COMMENT '十字',
  `CDLDOJISTAR` smallint(5) COMMENT '十字星 反转',
  `CDLDRAGONFLYDOJI` smallint(5) COMMENT '蜻蜓十字/T形十字 反转',
  `CDLGRAVESTONEDOJI` smallint(5) COMMENT '墓碑十字/倒T十字 底部反转',
  `CDLHAMMER` smallint(5) COMMENT '锤头 底部反转',
  `CDLHANGINGMAN` smallint(5) COMMENT '上吊线 顶部反转',
  `CDLLONGLEGGEDDOJI` smallint(5) COMMENT '长脚十字',
  `CDLLONGLINE` smallint(5) COMMENT '长蜡烛',
  `CDLMARUBOZU` smallint(5) COMMENT '光头光脚/缺影线',
  `CDLRICKSHAWMAN` smallint(5) COMMENT '黄包车夫',
  `CDLSHOOTINGSTAR` smallint(5) COMMENT '射击之星 看跌',
  `CDLSHORTLINE` smallint(5) COMMENT '短蜡烛',
  `CDLTAKURI` smallint(5) COMMENT '探水竿',
  `CDLCOUNTERATTACK` smallint(5) COMMENT '反击线 两日K',
  `CDLDARKCLOUDCOVER` smallint(5) COMMENT '乌云压顶 看跌 两日K',
  `CDLGAPSIDESIDEWHITE` smallint(5) COMMENT '向上/下跳空并列阳线 两日K',
  `CDLHARAMI` smallint(5) COMMENT '孕线 反转 两日K',
  `CDLHARAMICROSS` smallint(5) COMMENT '十字孕线 反转 两日K',
  `CDLHOMINGPIGEON` smallint(5) COMMENT '家鸽 两日K',
  `CDLINNECK` smallint(5) COMMENT '颈内线 两日K',
  `CDLKICKING` smallint(5) COMMENT '反冲形态 两日K',
  `CDLKICKINGBYLENGTH` smallint(5) COMMENT '由较长缺影线决定的反冲形态 两日K',
  `CDLMATCHINGLOW` smallint(5) COMMENT '相同低价 两日K',
  `CDLONNECK` smallint(5) COMMENT '颈上线 两日K',
  `CDLSEPARATINGLINES` smallint(5) COMMENT '分离线 两日K',
  `CDLTHRUSTING` smallint(5) COMMENT '插入 两日K',
  `CDLBELTHOLD` smallint(5) COMMENT '捉腰带线 两日K',
  `CDLENGULFING` smallint(5) COMMENT '吞噬模式 两日K',
  `CDLPIERCING` smallint(5) COMMENT '刺透形态 两日K',
  `CDL2CROWS` smallint(5) COMMENT '两只乌鸦 三日K',
  `CDL3BLACKCROWS` smallint(5) COMMENT '三只乌鸦 三日K',
  `CDL3INSIDE` smallint(5) COMMENT '三内部上涨和下跌 三日K',
  `CDL3OUTSIDE` smallint(5) COMMENT '三外部上涨和下跌 三日K',
  `CDL3STARSINSOUTH` smallint(5) COMMENT '南方三星 三日K',
  `CDLABANDONEDBABY` smallint(5) COMMENT '弃婴 三日K',
  `CDLUNIQUE3RIVER` smallint(5) COMMENT '奇特三川 三日K',
  `CDLMORNINGSTAR` smallint(5) COMMENT '早晨之星 三日K',
  `CDLMORNINGDOJISTAR` smallint(5) COMMENT '早晨十字星 三日K',
  `CDLEVENINGSTAR` smallint(5) COMMENT '黄昏之星 三日K',
  `CDLEVENINGDOJISTAR` smallint(5) COMMENT '黄昏十字星 三日K',
  `CDL3WHITESOLDIERS` smallint(5) COMMENT '三个白兵 三日K',
  `CDLADVANCEBLOCK` smallint(5) COMMENT '大敌当前 三日K',
  `CDLHIGHWAVE` smallint(5) COMMENT '风高浪大线 三日K',
  `CDLHIKKAKE` smallint(5) COMMENT '陷阱 三日K',
  `CDLHIKKAKEMOD` smallint(5) COMMENT '修正陷阱 三日K',
  `CDLIDENTICAL3CROWS` smallint(5) COMMENT '三胞胎乌鸦 三日K',
  `CDLSPINNINGTOP` smallint(5) COMMENT '纺锤 三日K',
  `CDLSTALLEDPATTERN` smallint(5) COMMENT '停顿形态 三日K',
  `CDLSTICKSANDWICH` smallint(5) COMMENT '条形三明治 三日K',
  `CDLTASUKIGAP` smallint(5) COMMENT '跳空并列阴阳线 三日K',
  `CDLTRISTAR` smallint(5) COMMENT '三星 三日K',
  `CDLUPSIDEGAP2CROWS` smallint(5) COMMENT '向上跳空的两只乌鸦 三日K',
  `CDL3LINESTRIKE` smallint(5) COMMENT '三线打击 四日K',
  `CDLCONCEALBABYSWALL` smallint(5) COMMENT '藏婴吞没 底部反转 四日K',
  `CDLBREAKAWAY` smallint(5) COMMENT '脱离 五日K',
  `CDLLADDERBOTTOM` smallint(5) COMMENT '梯底 五日K',
  `CDLMATHOLD` smallint(5) COMMENT '铺垫 五日K',
  `CDLRISEFALL3METHODS` smallint(5) COMMENT '上升/下降三法 五日K',
  `CDLXSIDEGAP3METHODS` smallint(5) COMMENT '上升/下降跳空三法 五日K'
);

CREATE INDEX `daily_pattern_signals_index_exchange` ON `daily_pattern_signals` (`exchange`);
CREATE INDEX `daily_pattern_signals_index_ts_code` ON `daily_pattern_signals` (`ts_code`);
CREATE INDEX `daily_pattern_signals_index_trade_date` ON `daily_pattern_signals` (`trade_date`);
CREATE UNIQUE INDEX `daily_pattern_signals_unique` ON `daily_pattern_signals` (`ts_code`, `trade_date`);