CREATE TABLE `stock_signals` (
  `id` integer PRIMARY KEY AUTO_INCREMENT,
  `ts_code` varchar(255) NOT NULL COMMENT 'TS代码',
  `exchange` varchar(255) NOT NULL COMMENT '交易所代码 SSE SZSE HK US',
  `yearly_price_position` tinyint(5),
  `yearly_price_position10` tinyint(5),
  `yearly_price_position20` tinyint(5),
  `yearly_price_position30` tinyint(5),
  `yearly_price_position50` tinyint(5),
  `yearly_price_position70` tinyint(5),
  `ma20_up` tinyint(2) COMMENT 'MA20上行',
  `ema20_up` tinyint(2) COMMENT 'EMA20上行',
  `ma30_up` tinyint(2) COMMENT 'MA30上行',
  `ema30_up` tinyint(2) COMMENT 'EMA30上行',
  `ma60_up` tinyint(2) COMMENT 'MA60上行',
  `ema60_up` tinyint(2) COMMENT 'EMA60上行',
  `ma120_up` tinyint(2) COMMENT 'MA120上行',
  `ema120_up` tinyint(2) COMMENT 'EMA120上行',
  `ma20_down` tinyint(2) COMMENT 'MA20下行',
  `ema20_down` tinyint(2) COMMENT 'EMA20下行',
  `ma30_down` tinyint(2) COMMENT 'MA30下行',
  `ema30_down` tinyint(2) COMMENT 'EMA30下行',
  `ma60_down` tinyint(2) COMMENT 'MA60下行',
  `ema60_down` tinyint(2) COMMENT 'EMA60下行',
  `ma120_down` tinyint(2) COMMENT 'MA120下行',
  `ema120_down` tinyint(2) COMMENT 'EMA120下行',
  `up_ma_arrange` tinyint(2) COMMENT 'MA多头排列（5/10/20/60）',
  `up_ema_arrange` tinyint(2) COMMENT 'EMA多头排列（5/10/20/60）',
  `down_ma_arrange` tinyint(2) COMMENT 'MA空头排列（5/10/20/60）',
  `down_ema_arrange` tinyint(2) COMMENT 'EMA空头排列（5/10/20/60）',
  `up_short_ma_arrange1` tinyint(2) COMMENT 'MA短期组合多头排列（5/10/20）',
  `up_short_ma_arrange2` tinyint(2) COMMENT 'MA短期组合多头排列（5/10/30）',
  `up_short_ema_arrange1` tinyint(2) COMMENT 'EMA短期组合多头排列（5/10/20）',
  `up_short_ema_arrange2` tinyint(2) COMMENT 'EMA短期组合多头排列（5/10/30）',
  `up_middle_ma_arrange1` tinyint(2) COMMENT 'MA中期组合多头排列（10/20/60）',
  `up_middle_ma_arrange2` tinyint(2) COMMENT 'MA中期组合多头排列（10/20/55）',
  `up_middle_ema_arrange1` tinyint(2) COMMENT 'EMA中期组合多头排列（10/20/60）',
  `up_middle_ema_arrange2` tinyint(2) COMMENT 'EMA中期组合多头排列（10/20/55）',
  `up_long_ma_arrange1` tinyint(2) COMMENT 'MA长期组合多头排列（20/55/120）',
  `up_long_ma_arrange2` tinyint(2) COMMENT 'MA长期组合多头排列（30/60/120）',
  `up_long_ema_arrange1` tinyint(2) COMMENT 'EMA长期组合多头排列（20/55/120）',
  `up_long_ema_arrange2` tinyint(2) COMMENT 'EMA长期组合多头排列（30/60/120）',
  `down_short_ma_arrange1` tinyint(2) COMMENT 'MA短期组合空头排列（5/10/20）',
  `down_short_ma_arrange2` tinyint(2) COMMENT 'MA短期组合空头排列（5/10/30）',
  `down_short_ema_arrange1` tinyint(2) COMMENT 'EMA短期组合空头排列（5/10/20）',
  `down_short_ema_arrange2` tinyint(2) COMMENT 'EMA短期组合空头排列（5/10/30）',
  `down_middle_ma_arrange1` tinyint(2) COMMENT 'MA中期组合空头排列（10/20/60）',
  `down_middle_ma_arrange2` tinyint(2) COMMENT 'MA中期组合空头排列（10/20/55）',
  `down_middle_ema_arrange1` tinyint(2) COMMENT 'EMA中期组合空头排列（10/20/60）',
  `down_middle_ema_arrange2` tinyint(2) COMMENT 'EMA中期组合空头排列（10/20/55）',
  `down_long_ma_arrange1` tinyint(2) COMMENT 'MA长期组合空头排列（20/55/120）',
  `down_long_ma_arrange2` tinyint(2) COMMENT 'MA长期组合空头排列（30/60/120）',
  `down_long_ema_arrange1` tinyint(2) COMMENT 'EMA长期组合空头排列（20/55/120）',
  `down_long_ema_arrange2` tinyint(2) COMMENT 'EMA长期组合空头排列（30/60/120）',
  `ma_gold_cross1` tinyint(2) COMMENT 'MA黄金交叉（5/10）',
  `ma_gold_cross2` tinyint(2) COMMENT 'MA黄金交叉（5/20）',
  `ma_gold_cross3` tinyint(2) COMMENT 'MA黄金交叉（10/20）',
  `ma_gold_cross4` tinyint(2) COMMENT 'MA黄金交叉（10/30）',
  `ma_dead_cross1` tinyint(2) COMMENT 'MA死亡交叉（5/10）',
  `ma_dead_cross2` tinyint(2) COMMENT 'MA死亡交叉（5/20）',
  `ma_dead_cross3` tinyint(2) COMMENT 'MA死亡交叉（10/20）',
  `ma_dead_cross4` tinyint(2) COMMENT 'MA死亡交叉（10/30）',
  `ma_silver_valley` tinyint(2) COMMENT 'MA银山谷（5/10，5/20，10/20）',
  `ma_gold_valley` tinyint(2) COMMENT 'MA金山谷（5/10，5/20，10/20）',
  `ma_dead_valley` tinyint(2) COMMENT 'MA死亡谷（5/10，5/20，10/20）',
  `ma_glue` tinyint(1) COMMENT 'MA均线粘合',
  `ma_out_sea` tinyint(2) COMMENT 'MA蛟龙出海(5/10/20)',
  `ma_hold_moon` tinyint(2) COMMENT 'MA烘云托月(5/10/20)',
  `ma_over_gate` tinyint(2) COMMENT 'MA鱼跃龙门(5/10/20)',
  `ma_up_ground` tinyint(2) COMMENT 'MA旱地拔葱(5/10/20)',
  `ma_knife` tinyint(2) COMMENT 'MA断头铡刀(5/10/20)',
  `ma_dark_cloud` tinyint(2) COMMENT 'MA乌云密布(5/10/20)',
  `ma_set_sail` tinyint(2) COMMENT 'MA战机起航(5/10/20)',
  `ma_supreme` tinyint(2) COMMENT 'MA气贯长虹(5/10/20)',
  `ma_dead_jump` tinyint(2) COMMENT 'MA绝命跳(5/10/20)',
  `up_ma_spider` tinyint(2) COMMENT 'MA金蜘蛛',
  `down_ma_spider` tinyint(2) COMMENT 'MA毒蜘蛛',
  `up_hill` tinyint(2) COMMENT 'MA上山爬坡',
  `down_hill` tinyint(2) COMMENT 'MA下山滑坡',
  `up_td8` tinyint(2),
  `up_td9` tinyint(2),
  `down_td8` tinyint(2),
  `down_td9` tinyint(2),
  `up_bias6` tinyint(2) COMMENT '正乖离(超买)',
  `up_bias12` tinyint(2),
  `up_bias24` tinyint(2),
  `up_bias60` tinyint(2),
  `up_bias72` tinyint(2),
  `up_bias120` tinyint(2),
  `down_bias6` tinyint(2) COMMENT '负乖离(超卖)',
  `down_bias12` tinyint(2),
  `down_bias24` tinyint(2),
  `down_bias60` tinyint(2),
  `down_bias72` tinyint(2),
  `down_bias120` tinyint(2),
  `ma60_support` tinyint(2),
  `ma120_support` tinyint(2),
  `stand_up_ma60` tinyint(1),
  `stand_up_ma120` tinyint(1),
  `hammer` tinyint(1) COMMENT '锤头线(long)',
  `pour_hammer` tinyint(1) COMMENT '倒锤头线(long)',
  `short_end` tinyint(1) COMMENT '尽头线(long)',
  `long_end` tinyint(1) COMMENT '尽头线(short)',
  `swallow_up` tinyint(1) COMMENT '看涨吞没(long)',
  `swallow_down` tinyint(1) COMMENT '看跌吞没(short)',
  `attack_short` tinyint(1) COMMENT '好友反攻(long)',
  `first_light` tinyint(1) COMMENT '曙光初现(long)',
  `sunrise` tinyint(1) COMMENT '旭日东升(long)',
  `flat_base` tinyint(1) COMMENT '平底(long)',
  `hang_neck` tinyint(1) COMMENT '吊颈线(short)',
  `shooting` tinyint(1) COMMENT '射击之星(short)',
  `rise_line` tinyint(1) COMMENT '涨停一字线(long)',
  `drop_line` tinyint(1) COMMENT '跌停一字线(short)',
  `up_screw` tinyint(1) COMMENT '上涨螺旋桨(short)',
  `down_screw` tinyint(1) COMMENT '下跌螺旋桨(long)',
  `ma55_first` tinyint(1),
  `ma55_second` tinyint(1),
  `ma55_third` tinyint(1),
  `ma55_fourth` tinyint(1),
  `ma55_fifth` tinyint(1),
  `ma55_sixth` tinyint(1),
  `ma55_seventh` tinyint(1),
  `ma55_eighth` tinyint(1),
  `ma60_first` tinyint(1),
  `ma60_second` tinyint(1),
  `ma60_third` tinyint(1),
  `ma60_fourth` tinyint(1),
  `ma60_fifth` tinyint(1),
  `ma60_sixth` tinyint(1),
  `ma60_seventh` tinyint(1),
  `ma60_eighth` tinyint(1),
  `hlines` varchar(255) COMMENT '水平位',
  `limit_pullback` tinyint(1) COMMENT '涨停回调',
  `up_pullback` tinyint(1) COMMENT '上涨回调',
  `down_pullback` tinyint(1) COMMENT '下跌反弹',
  `up_break` tinyint(1) COMMENT '向上突破',
  `down_break` tinyint(1) COMMENT '向下突破',
  `hline_support` tinyint(1) COMMENT '水平支撑',
  `hline_resistance` tinyint(1) COMMENT '水平阻力'
);

CREATE INDEX `stock_signals_index_exchange` ON `stock_signals` (`exchange`);
CREATE INDEX `stock_signals_index_ts_code` ON `stock_signals` (`ts_code`);
