CREATE TABLE `stocks` (
  `id` integer PRIMARY KEY AUTO_INCREMENT,
  `ts_code` varchar(255) UNIQUE NOT NULL COMMENT 'TS代码',
  `symbol` varchar(255) COMMENT '股票代码',
  `name` varchar(255) COMMENT '股票名称',
  `area` varchar(255) COMMENT '地域',
  `industry` varchar(255) COMMENT '所属行业',
  `fullname` varchar(255) COMMENT '股票全称',
  `enname` varchar(255) COMMENT '英文全称',
  `cnspell` varchar(255) COMMENT '拼音缩写',
  `market` varchar(255) COMMENT '市场类型',
  `exchange` varchar(255) NOT NULL COMMENT '交易所代码 SSE SZSE HK US',
  `list_status` varchar(255) COMMENT '上市状态 L上市 D退市 P暂停上市',
  `list_date` varchar(255) COMMENT '上市日期',
  `delist_date` varchar(255) COMMENT '退市日期',
  `is_hs` varchar(255) COMMENT '是否沪深港通标的，N否 H沪股通 S深股通',
  `turnover_rate` float COMMENT '换手率',
  `turnover_rate_f` float COMMENT '换手率(自由流通股)',
  `volume_ratio` float COMMENT '量比',
  `pe` float COMMENT '市盈率（总市值/净利润）',
  `pe_ttm` float COMMENT '市盈率（TTM）',
  `pb` float COMMENT '市净率（总市值/净资产）',
  `ps` float COMMENT '市销率',
  `ps_ttm` float COMMENT '市销率（TTM）',
  `dv_ratio` float COMMENT '股息率（%）',
  `dv_ttm` float COMMENT '股息率（TTM)（%）',
  `total_share` float COMMENT '总股本',
  `float_share` float COMMENT '流通股本',
  `free_share` float COMMENT '自由流通股本',
  `total_mv` float COMMENT '总市值',
  `circ_mv` float COMMENT '流通市值',
  `scan_date` date COMMENT '扫描买卖信号日期',
  `candle_date` date COMMENT '更新日K日期',
  `indicator_date` date COMMENT '更新indicator日期',
  `weekly_candle_date` date COMMENT '更新周K日期',
  `amount` float COMMENT '成交额'
);

CREATE INDEX `stocks_index_exchange` ON `stocks` (`exchange`);
CREATE INDEX `stocks_index_ts_code` ON `stocks` (`ts_code`);
