CREATE TABLE `us_daily_signals` (
  `id` int NOT NULL AUTO_INCREMENT,
  `ts_code` varchar(255) NOT NULL COMMENT 'TS代码',
  `exchange` varchar(255) NOT NULL COMMENT '交易所代码 SSE SZSE HK US',
  `trade_date` date NOT NULL COMMENT '交易日期',
  `ma20_up` tinyint DEFAULT NULL COMMENT 'MA20上行',
  `ema20_up` tinyint DEFAULT NULL COMMENT 'EMA20上行',
  `ma30_up` tinyint DEFAULT NULL COMMENT 'MA30上行',
  `ema30_up` tinyint DEFAULT NULL COMMENT 'EMA30上行',
  `ma60_up` tinyint DEFAULT NULL COMMENT 'MA60上行',
  `ema60_up` tinyint DEFAULT NULL COMMENT 'EMA60上行',
  `ma120_up` tinyint DEFAULT NULL COMMENT 'MA120上行',
  `ema120_up` tinyint DEFAULT NULL COMMENT 'EMA120上行',
  `ma20_down` tinyint DEFAULT NULL COMMENT 'MA20下行',
  `ema20_down` tinyint DEFAULT NULL COMMENT 'EMA20下行',
  `ma30_down` tinyint DEFAULT NULL COMMENT 'MA30下行',
  `ema30_down` tinyint DEFAULT NULL COMMENT 'EMA30下行',
  `ma60_down` tinyint DEFAULT NULL COMMENT 'MA60下行',
  `ema60_down` tinyint DEFAULT NULL COMMENT 'EMA60下行',
  `ma120_down` tinyint DEFAULT NULL COMMENT 'MA120下行',
  `ema120_down` tinyint DEFAULT NULL COMMENT 'EMA120下行',
  `up_ma_arrange` tinyint DEFAULT NULL COMMENT 'MA多头排列（5/10/20/60）',
  `up_ema_arrange` tinyint DEFAULT NULL COMMENT 'EMA多头排列（5/10/20/60）',
  `down_ma_arrange` tinyint DEFAULT NULL COMMENT 'MA空头排列（5/10/20/60）',
  `down_ema_arrange` tinyint DEFAULT NULL COMMENT 'EMA空头排列（5/10/20/60）',
  `up_short_ma_arrange1` tinyint DEFAULT NULL COMMENT 'MA短期组合多头排列（5/10/20）',
  `up_short_ma_arrange2` tinyint DEFAULT NULL COMMENT 'MA短期组合多头排列（5/10/30）',
  `up_short_ema_arrange1` tinyint DEFAULT NULL COMMENT 'EMA短期组合多头排列（5/10/20）',
  `up_short_ema_arrange2` tinyint DEFAULT NULL COMMENT 'EMA短期组合多头排列（5/10/30）',
  `up_middle_ma_arrange1` tinyint DEFAULT NULL COMMENT 'MA中期组合多头排列（10/20/60）',
  `up_middle_ma_arrange2` tinyint DEFAULT NULL COMMENT 'MA中期组合多头排列（10/20/55）',
  `up_middle_ema_arrange1` tinyint DEFAULT NULL COMMENT 'EMA中期组合多头排列（10/20/60）',
  `up_middle_ema_arrange2` tinyint DEFAULT NULL COMMENT 'EMA中期组合多头排列（10/20/55）',
  `up_long_ma_arrange1` tinyint DEFAULT NULL COMMENT 'MA长期组合多头排列（20/55/120）',
  `up_long_ma_arrange2` tinyint DEFAULT NULL COMMENT 'MA长期组合多头排列（30/60/120）',
  `up_long_ema_arrange1` tinyint DEFAULT NULL COMMENT 'EMA长期组合多头排列（20/55/120）',
  `up_long_ema_arrange2` tinyint DEFAULT NULL COMMENT 'EMA长期组合多头排列（30/60/120）',
  `down_short_ma_arrange1` tinyint DEFAULT NULL COMMENT 'MA短期组合空头排列（5/10/20）',
  `down_short_ma_arrange2` tinyint DEFAULT NULL COMMENT 'MA短期组合空头排列（5/10/30）',
  `down_short_ema_arrange1` tinyint DEFAULT NULL COMMENT 'EMA短期组合空头排列（5/10/20）',
  `down_short_ema_arrange2` tinyint DEFAULT NULL COMMENT 'EMA短期组合空头排列（5/10/30）',
  `down_middle_ma_arrange1` tinyint DEFAULT NULL COMMENT 'MA中期组合空头排列（10/20/60）',
  `down_middle_ma_arrange2` tinyint DEFAULT NULL COMMENT 'MA中期组合空头排列（10/20/55）',
  `down_middle_ema_arrange1` tinyint DEFAULT NULL COMMENT 'EMA中期组合空头排列（10/20/60）',
  `down_middle_ema_arrange2` tinyint DEFAULT NULL COMMENT 'EMA中期组合空头排列（10/20/55）',
  `down_long_ma_arrange1` tinyint DEFAULT NULL COMMENT 'MA长期组合空头排列（20/55/120）',
  `down_long_ma_arrange2` tinyint DEFAULT NULL COMMENT 'MA长期组合空头排列（30/60/120）',
  `down_long_ema_arrange1` tinyint DEFAULT NULL COMMENT 'EMA长期组合空头排列（20/55/120）',
  `down_long_ema_arrange2` tinyint DEFAULT NULL COMMENT 'EMA长期组合空头排列（30/60/120）',
  `ma_gold_cross1` tinyint DEFAULT NULL COMMENT 'MA黄金交叉（5/10）',
  `ma_gold_cross2` tinyint DEFAULT NULL COMMENT 'MA黄金交叉（5/20）',
  `ma_gold_cross3` tinyint DEFAULT NULL COMMENT 'MA黄金交叉（10/20）',
  `ma_gold_cross4` tinyint DEFAULT NULL COMMENT 'MA黄金交叉（10/30）',
  `ma_dead_cross1` tinyint DEFAULT NULL COMMENT 'MA死亡交叉（5/10）',
  `ma_dead_cross2` tinyint DEFAULT NULL COMMENT 'MA死亡交叉（5/20）',
  `ma_dead_cross3` tinyint DEFAULT NULL COMMENT 'MA死亡交叉（10/20）',
  `ma_dead_cross4` tinyint DEFAULT NULL COMMENT 'MA死亡交叉（10/30）',
  `ma_silver_valley` tinyint DEFAULT NULL COMMENT 'MA银山谷（5/10，5/20，10/20）',
  `ma_gold_valley` tinyint DEFAULT NULL COMMENT 'MA金山谷（5/10，5/20，10/20）',
  `ma_out_sea` tinyint DEFAULT NULL COMMENT 'MA蛟龙出海(5/10/20)',
  `ma_hold_moon` tinyint DEFAULT NULL COMMENT 'MA烘云托月(5/10/20)',
  `ma_over_gate` tinyint DEFAULT NULL COMMENT 'MA鱼跃龙门(5/10/20)',
  `ma_up_ground` tinyint DEFAULT NULL COMMENT 'MA旱地拔葱(5/10/20)',
  `ma_dead_valley` tinyint DEFAULT NULL COMMENT 'MA死亡谷（5/10，5/20，10/20）',
  `ma_knife` tinyint DEFAULT NULL COMMENT 'MA断头铡刀(5/10/20)',
  `ma_dark_cloud` tinyint DEFAULT NULL COMMENT 'MA乌云密布(5/10/20)',
  `ma_set_sail` tinyint DEFAULT NULL COMMENT 'MA战机起航(5/10/20)',
  `ma_supreme` tinyint DEFAULT NULL COMMENT 'MA气贯长虹(5/10/20)',
  `ma_dead_jump` tinyint DEFAULT NULL COMMENT 'MA绝命跳(5/10/20)',
  `up_ma_spider` tinyint DEFAULT NULL COMMENT 'MA金蜘蛛',
  `down_ma_spider` tinyint DEFAULT NULL COMMENT 'MA毒蜘蛛',
  `ma_glue` tinyint(1) DEFAULT NULL COMMENT 'MA均线粘合',
  `up_hill` tinyint DEFAULT NULL COMMENT 'MA上山爬坡',
  `down_hill` tinyint DEFAULT NULL COMMENT 'MA下山滑坡',
  `up_td8` tinyint DEFAULT NULL,
  `up_td9` tinyint DEFAULT NULL,
  `down_td8` tinyint DEFAULT NULL,
  `down_td9` tinyint DEFAULT NULL,
  `up_bias6` tinyint DEFAULT NULL COMMENT '正乖离(超买)',
  `up_bias12` tinyint DEFAULT NULL,
  `up_bias24` tinyint DEFAULT NULL,
  `up_bias60` tinyint DEFAULT NULL,
  `up_bias72` tinyint DEFAULT NULL,
  `up_bias120` tinyint DEFAULT NULL,
  `down_bias6` tinyint DEFAULT NULL COMMENT '负乖离(超卖)',
  `down_bias12` tinyint DEFAULT NULL,
  `down_bias24` tinyint DEFAULT NULL,
  `down_bias60` tinyint DEFAULT NULL,
  `down_bias72` tinyint DEFAULT NULL,
  `down_bias120` tinyint DEFAULT NULL,
  `ma60_support` tinyint DEFAULT NULL,
  `ma120_support` tinyint DEFAULT NULL,
  `stand_up_ma60` tinyint(1) DEFAULT NULL,
  `stand_up_ma120` tinyint(1) DEFAULT NULL,
  `hammer` tinyint(1) DEFAULT NULL COMMENT '锤头线(long)',
  `pour_hammer` tinyint(1) DEFAULT NULL COMMENT '倒锤头线(long)',
  `short_end` tinyint(1) DEFAULT NULL COMMENT '尽头线(long)',
  `long_end` tinyint(1) DEFAULT NULL COMMENT '尽头线(short)',
  `swallow_up` tinyint(1) DEFAULT NULL COMMENT '看涨吞没(long)',
  `swallow_down` tinyint(1) DEFAULT NULL COMMENT '看跌吞没(short)',
  `attack_short` tinyint(1) DEFAULT NULL COMMENT '好友反攻(long)',
  `first_light` tinyint(1) DEFAULT NULL COMMENT '曙光初现(long)',
  `sunrise` tinyint(1) DEFAULT NULL COMMENT '旭日东升(long)',
  `flat_base` tinyint(1) DEFAULT NULL COMMENT '平底(long)',
  `hang_neck` tinyint(1) DEFAULT NULL COMMENT '吊颈线(short)',
  `shooting` tinyint(1) DEFAULT NULL COMMENT '射击之星(short)',
  `up_screw` tinyint(1) DEFAULT NULL COMMENT '上涨螺旋桨(short)',
  `down_screw` tinyint(1) DEFAULT NULL COMMENT '下跌螺旋桨(long)',
  `ma60_first` tinyint(1) DEFAULT NULL,
  `ma60_second` tinyint(1) DEFAULT NULL,
  `ma60_third` tinyint(1) DEFAULT NULL,
  `ma60_fourth` tinyint(1) DEFAULT NULL,
  `ma60_fifth` tinyint(1) DEFAULT NULL,
  `ma60_sixth` tinyint(1) DEFAULT NULL,
  `ma60_seventh` tinyint(1) DEFAULT NULL,
  `ma60_eighth` tinyint(1) DEFAULT NULL,
  `down_rise` tinyint DEFAULT NULL COMMENT '下探上涨',
  `upward_jump` tinyint DEFAULT NULL COMMENT '向上跳空',
  `downward_jump` tinyint DEFAULT NULL COMMENT '向下跳空',
  `up_cross3ma` tinyint DEFAULT NULL COMMENT '一阳穿三线',
  `up_cross4ma` tinyint DEFAULT NULL COMMENT '一阳穿四线',
  `drop_cross3ma` tinyint DEFAULT NULL COMMENT '一阴穿三线',
  `drop_cross4ma` tinyint DEFAULT NULL COMMENT '一阴穿三线',
  `max_vol` tinyint DEFAULT NULL COMMENT '天量',
  `huge_vol` tinyint DEFAULT NULL COMMENT '巨量',
  `large_vol` tinyint DEFAULT NULL COMMENT '大量',
  `high_vol` tinyint DEFAULT NULL COMMENT '高量',
  `common_vol` tinyint DEFAULT NULL COMMENT '常量',
  `low_vol` tinyint DEFAULT NULL COMMENT '地量',
  `increase_vol` tinyint DEFAULT NULL COMMENT '放量',
  `decrease_vol` tinyint DEFAULT NULL COMMENT '缩量',
  `increasingly_vol` tinyint DEFAULT NULL COMMENT '持续放量',
  `decreasingly_vol` tinyint DEFAULT NULL COMMENT '持续缩量',
  `ma_rule_marker` tinyint DEFAULT NULL COMMENT '葛南维买卖法则信号',
  `up_wave` tinyint DEFAULT NULL COMMENT '逐浪上升',
  PRIMARY KEY (`id`),
  UNIQUE KEY `us_daily_signals_unique` (`ts_code`,`trade_date`),
  KEY `us_daily_signals_index_exchange` (`exchange`),
  KEY `us_daily_signals_index_ts_code` (`ts_code`),
  KEY `us_daily_signals_index_trade_date` (`trade_date`),
  KEY `us_daily_signals_index_ma_rule_marker` (`ma_rule_marker`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;