CREATE TABLE `us_weekly_candles` (
  `id` int NOT NULL AUTO_INCREMENT,
  `ts_code` varchar(255) NOT NULL COMMENT 'TS代码',
  `trade_date` date NOT NULL COMMENT '交易日期',
  `open` float DEFAULT NULL,
  `high` float DEFAULT NULL,
  `low` float DEFAULT NULL,
  `close` float DEFAULT NULL,
  `pre_close` float DEFAULT NULL,
  `chg` float DEFAULT NULL,
  `pct_chg` float DEFAULT NULL,
  `vol` float DEFAULT NULL,
  `amount` float DEFAULT NULL,
  `ma5` float DEFAULT NULL,
  `ma10` float DEFAULT NULL,
  `ma20` float DEFAULT NULL,
  `ma30` float DEFAULT NULL,
  `ma60` float DEFAULT NULL,
  `ema5` float DEFAULT NULL,
  `ema10` float DEFAULT NULL,
  `ema20` float DEFAULT NULL,
  `ema30` float DEFAULT NULL,
  `ema60` float DEFAULT NULL,
  `diff` float DEFAULT NULL,
  `dea` float DEFAULT NULL,
  `macd` float DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `weekly_candle_unique` (`ts_code`,`trade_date`),
  KEY `us_weekly_candles_index_23` (`ts_code`),
  KEY `us_weekly_candles_index_24` (`trade_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;