CREATE TABLE `weekly_signals` (
  `id` integer PRIMARY KEY AUTO_INCREMENT,
  `ts_code` varchar(255) NOT NULL COMMENT 'TS代码',
  `trade_date` date NOT NULL COMMENT '交易日期',
  `ma20_up` tinyint(2) COMMENT 'MA20上行',
  `ema20_up` tinyint(2) COMMENT 'EMA20上行',
  `ma30_up` tinyint(2) COMMENT 'MA30上行',
  `ema30_up` tinyint(2) COMMENT 'EMA30上行',
  `ma60_up` tinyint(2) COMMENT 'MA60上行',
  `ema60_up` tinyint(2) COMMENT 'EMA60上行',
  `ma20_down` tinyint(2) COMMENT 'MA20下行',
  `ema20_down` tinyint(2) COMMENT 'EMA20下行',
  `ma30_down` tinyint(2) COMMENT 'MA30下行',
  `ema30_down` tinyint(2) COMMENT 'EMA30下行',
  `ma60_down` tinyint(2) COMMENT 'MA60下行',
  `ema60_down` tinyint(2) COMMENT 'EMA60下行',
  `up_ma_arrange` tinyint(2) COMMENT 'MA多头排列（5/10/20/60）',
  `up_ema_arrange` tinyint(2) COMMENT 'EMA多头排列（5/10/20/60）',
  `down_ma_arrange` tinyint(2) COMMENT 'MA空头排列（5/10/20/60）',
  `down_ema_arrange` tinyint(2) COMMENT 'EMA空头排列（5/10/20/60）',
  `up_short_ma_arrange1` tinyint(2) COMMENT 'MA短期组合多头排列（5/10/20）',
  `up_short_ma_arrange2` tinyint(2) COMMENT 'MA短期组合多头排列（5/10/30）',
  `up_short_ema_arrange1` tinyint(2) COMMENT 'EMA短期组合多头排列（5/10/20）',
  `up_short_ema_arrange2` tinyint(2) COMMENT 'EMA短期组合多头排列（5/10/30）',
  `down_short_ma_arrange1` tinyint(2) COMMENT 'MA短期组合空头排列（5/10/20）',
  `down_short_ma_arrange2` tinyint(2) COMMENT 'MA短期组合空头排列（5/10/30）',
  `ma_gold_cross1` tinyint(2) COMMENT 'MA黄金交叉（5/10）',
  `ma_gold_cross2` tinyint(2) COMMENT 'MA黄金交叉（5/20）',
  `ma_gold_cross3` tinyint(2) COMMENT 'MA黄金交叉（10/20）',
  `ma_gold_cross4` tinyint(2) COMMENT 'MA黄金交叉（10/30）',
  `ma_dead_cross1` tinyint(2) COMMENT 'MA死亡交叉（5/10）',
  `ma_dead_cross2` tinyint(2) COMMENT 'MA死亡交叉（5/20）',
  `ma_dead_cross3` tinyint(2) COMMENT 'MA死亡交叉（10/20）',
  `ma_silver_valley` tinyint(2) COMMENT 'MA银山谷（5/10，5/20，10/20）',
  `ma_gold_valley` tinyint(2) COMMENT 'MA金山谷（5/10，5/20，10/20）',
  `ma_out_sea` tinyint(2) COMMENT 'MA蛟龙出海(5/10/20)',
  `ma_hold_moon` tinyint(2) COMMENT 'MA烘云托月(5/10/20)',
  `ma_over_gate` tinyint(2) COMMENT 'MA鱼跃龙门(5/10/20)',
  `ma_up_ground` tinyint(2) COMMENT 'MA旱地拔葱(5/10/20)',
  `ma_dead_valley` tinyint(2) COMMENT 'MA死亡谷（5/10，5/20，10/20）',
  `ma_knife` tinyint(2) COMMENT 'MA断头铡刀(5/10/20)',
  `ma_dark_cloud` tinyint(2) COMMENT 'MA乌云密布(5/10/20)',
  `ma_set_sail` tinyint(2) COMMENT 'MA战机起航(5/10/20)',
  `ma_supreme` tinyint(2) COMMENT 'MA气贯长虹(5/10/20)',
  `ma_dead_jump` tinyint(2) COMMENT 'MA绝命跳(5/10/20)',
  `up_ma_spider` tinyint(2) COMMENT 'MA金蜘蛛',
  `down_ma_spider` tinyint(2) COMMENT 'MA毒蜘蛛',
  `ma_glue` tinyint(1) COMMENT 'MA均线粘合',
  `up_hill` tinyint(2) COMMENT 'MA上山爬坡',
  `down_hill` tinyint(2) COMMENT 'MA下山滑坡',
  `ma60_support` tinyint(2),
  `ma_up_arrange51020` tinyint(1),
  `ma_up_arrange5102030` tinyint(1),
  `ma_up_arrange510203060` tinyint(1),
  `ma_down_arrange51020` tinyint(1),
  `ma_down_arrange5102030` tinyint(1),
  `ma_down_arrange510203060` tinyint(1),
  `hammer` tinyint(1) COMMENT '锤头线(long)',
  `pour_hammer` tinyint(1) COMMENT '倒锤头线(long)',
  `short_end` tinyint(1) COMMENT '尽头线(long)',
  `long_end` tinyint(1) COMMENT '尽头线(short)',
  `swallow_up` tinyint(1) COMMENT '看涨吞没(long)',
  `swallow_down` tinyint(1) COMMENT '看跌吞没(short)',
  `attack_short` tinyint(1) COMMENT '好友反攻(long)',
  `first_light` tinyint(1) COMMENT '曙光初现(long)',
  `sunrise` tinyint(1) COMMENT '旭日东升(long)',
  `flat_base` tinyint(1) COMMENT '平底(long)',
  `hang_neck` tinyint(1) COMMENT '吊颈线(short)',
  `shooting` tinyint(1) COMMENT '射击之星(short)',
  `up_screw` tinyint(1) COMMENT '上涨螺旋桨(short)',
  `down_screw` tinyint(1) COMMENT '下跌螺旋桨(long)'
);

CREATE INDEX `weekly_signals_index_ts_code` ON `weekly_signals` (`ts_code`);
CREATE INDEX `weekly_signals_index_trade_date` ON `weekly_signals` (`trade_date`);
CREATE UNIQUE INDEX `weekly_signals_unique` ON `weekly_signals` (`ts_code`, `trade_date`);