CREATE TABLE `weekly_long_signals` (
  `id` integer PRIMARY KEY AUTO_INCREMENT,
  `ts_code` varchar(255) NOT NULL COMMENT 'TS代码',
  `trade_date` date NOT NULL COMMENT '交易日期',
  `ma20_up` tinyint(2) COMMENT 'MA20上行',
  `ema20_up` tinyint(2) COMMENT 'EMA20上行',
  `ma30_up` tinyint(2) COMMENT 'MA30上行',
  `ema30_up` tinyint(2) COMMENT 'EMA30上行',
  `ma60_up` tinyint(2) COMMENT 'MA60上行',
  `ema60_up` tinyint(2) COMMENT 'EMA60上行',
  `ma_arrange` tinyint(2) COMMENT 'MA多头排列（5/10/20/60）',
  `ema_arrange` tinyint(2) COMMENT 'EMA多头排列（5/10/20/60）',
  `short_ma_arrange1` tinyint(2) COMMENT 'MA短期组合多头排列（5/10/20）',
  `short_ma_arrange2` tinyint(2) COMMENT 'MA短期组合多头排列（5/10/30）',
  `short_ema_arrange1` tinyint(2) COMMENT 'EMA短期组合多头排列（5/10/20）',
  `short_ema_arrange2` tinyint(2) COMMENT 'EMA短期组合多头排列（5/10/30）',
  `middle_ma_arrange1` tinyint(2) COMMENT 'MA中期组合多头排列（10/20/60）',
  `middle_ma_arrange2` tinyint(2) COMMENT 'MA中期组合多头排列（10/20/55）',
  `middle_ema_arrange1` tinyint(2) COMMENT 'EMA中期组合多头排列（10/20/60）',
  `middle_ema_arrange2` tinyint(2) COMMENT 'EMA中期组合多头排列（10/20/55）',
  `ma_gold_cross1` tinyint(2) COMMENT 'MA黄金交叉（5/10）',
  `ma_gold_cross2` tinyint(2) COMMENT 'MA黄金交叉（5/20）',
  `ma_gold_cross3` tinyint(2) COMMENT 'MA黄金交叉（10/20）',
  `ma_gold_cross4` tinyint(2) COMMENT 'MA黄金交叉（10/30）',
  `ema_gold_cross1` tinyint(2) COMMENT 'EMA黄金交叉（5/10）',
  `ema_gold_cross2` tinyint(2) COMMENT 'EMA黄金交叉（5/20）',
  `ema_gold_cross3` tinyint(2) COMMENT 'EMA黄金交叉（10/20）',
  `ema_gold_cross4` tinyint(2) COMMENT 'EMA黄金交叉（10/30）',
  `ma_out_sea` tinyint(2) COMMENT 'MA蛟龙出海(5/10/20)',
  `ema_out_sea` tinyint(2) COMMENT 'EMA蛟龙出海(5/10/20)',
  `ma_hold_moon` tinyint(2) COMMENT 'MA烘云托月(5/10/20)',
  `ema_hold_moon` tinyint(2) COMMENT 'EMA烘云托月(5/10/20)',
  `ma_over_gate` tinyint(2) COMMENT 'MA鱼跃龙门(5/10/20)',
  `ema_over_gate` tinyint(2) COMMENT 'EMA鱼跃龙门(5/10/20)',
  `ma_up_group` tinyint(2) COMMENT 'MA旱地拔葱(5/10/20)',
  `ema_up_group` tinyint(2) COMMENT 'EMA旱地拔葱(5/10/20)',
  `ma_group_glue` tinyint(1),
  `ema_group_glue` tinyint(1),
  `ma_up_arrange51020` tinyint(1),
  `ma_up_arrange5102030` tinyint(1),
  `ma_up_arrange510203060` tinyint(1),
  `ema_up_arrange51020` tinyint(1),
  `ema_up_arrange5102030` tinyint(1),
  `ema_up_arrange510203060` tinyint(1)
);

CREATE INDEX `weekly_long_signals_index_ts_code` ON `weekly_long_signals` (`ts_code`);
CREATE INDEX `weekly_long_signals_index_trade_date` ON `weekly_long_signals` (`trade_date`);
CREATE UNIQUE INDEX `weekly_long_signals_unique` ON `weekly_long_signals` (`ts_code`, `trade_date`);