CREATE TABLE `trade_calendar` (
  `id` integer PRIMARY KEY AUTO_INCREMENT,
  `exchange` varchar(255) NOT NULL COMMENT '交易所 SSE上交所 SZSE深交所 HK 港交所 US 美交所',
  `cal_date` date NOT NULL COMMENT '日历日期',
  `is_open` tinyint NOT NULL COMMENT '是否交易 0休市 1交易',
  `pretrade_date` date COMMENT '上一个交易日',
  `candle_ready` tinyint NOT NULL DEFAULT 0 COMMENT '日K是否获取完成 0否 1是',
  `basic_ready` tinyint NOT NULL DEFAULT 0 COMMENT '每日指标是获取完成 0否 1是',
  `talib_ready` tinyint NOT NULL DEFAULT 0 COMMENT 'talib指标是计算完成 0否 1是'
);

CREATE TABLE `stocks` (
  `id` integer PRIMARY KEY AUTO_INCREMENT,
  `ts_code` varchar(255) UNIQUE NOT NULL COMMENT 'TS代码',
  `symbol` varchar(255) COMMENT '股票代码',
  `name` varchar(255) COMMENT '股票名称',
  `area` varchar(255) COMMENT '地域',
  `industry` varchar(255) COMMENT '所属行业',
  `fullname` varchar(255) COMMENT '股票全称',
  `enname` varchar(255) COMMENT '英文全称',
  `cnspell` varchar(255) COMMENT '拼音缩写',
  `market` varchar(255) COMMENT '市场类型',
  `exchange` varchar(255) NOT NULL COMMENT '交易所代码 SSE SZSE HK US',
  `list_status` varchar(255) COMMENT '上市状态 L上市 D退市 P暂停上市',
  `list_date` varchar(255) COMMENT '上市日期',
  `delist_date` varchar(255) COMMENT '退市日期',
  `is_hs` varchar(255) COMMENT '是否沪深港通标的，N否 H沪股通 S深股通',
  `turnover_rate` float COMMENT '换手率',
  `turnover_rate_f` float COMMENT '换手率(自由流通股)',
  `volume_ratio` float COMMENT '量比',
  `pe` float COMMENT '市盈率（总市值/净利润）',
  `pe_ttm` float COMMENT '市盈率（TTM）',
  `pb` float COMMENT '市净率（总市值/净资产）',
  `ps` float COMMENT '市销率',
  `ps_ttm` float COMMENT '市销率（TTM）',
  `dv_ratio` float COMMENT '股息率（%）',
  `dv_ttm` float COMMENT '股息率（TTM)（%）',
  `total_share` float COMMENT '总股本',
  `float_share` float COMMENT '流通股本',
  `free_share` float COMMENT '自由流通股本',
  `total_mv` float COMMENT '总市值',
  `circ_mv` float COMMENT '流通市值',
  `scan_date` date COMMENT '扫描买卖信号日期',
  `candle_date` date COMMENT '更新日K日期',
  `indicator_date` date COMMENT '更新indicator日期',
  `weekly_candle_date` date COMMENT '更新周K日期',
  `amount` float COMMENT '成交额'
);

CREATE TABLE `cn_daily_candles` (
  `id` integer PRIMARY KEY AUTO_INCREMENT,
  `ts_code` varchar(255) NOT NULL COMMENT 'TS代码',
  `trade_date` date NOT NULL COMMENT '交易日期',
  `open` float,
  `high` float,
  `low` float,
  `close` float,
  `pre_close` float COMMENT '昨收价',
  `change` float COMMENT '涨跌额',
  `pct_chg` float COMMENT '涨跌幅',
  `vol` float COMMENT '成交量',
  `amount` float COMMENT '成交额',
  `turnover_rate` float COMMENT '换手率',
  `turnover_rate_f` float COMMENT '换手率(自由流通股)',
  `volume_ratio` float COMMENT '量比',
  `pe` float COMMENT '市盈率（总市值/净利润）',
  `pe_ttm` float COMMENT '市盈率（TTM）',
  `pb` float COMMENT '市净率（总市值/净资产）',
  `ps` float COMMENT '市销率',
  `ps_ttm` float COMMENT '市销率（TTM）',
  `dv_ratio` float COMMENT '股息率（%）',
  `dv_ttm` float COMMENT '股息率（TTM)（%）',
  `total_share` float COMMENT '总股本',
  `float_share` float COMMENT '流通股本',
  `free_share` float COMMENT '自由流通股本',
  `total_mv` float COMMENT '总市值',
  `circ_mv` float COMMENT '流通市值'
);

CREATE TABLE `hk_daily_candles` (
  `id` integer PRIMARY KEY AUTO_INCREMENT,
  `ts_code` varchar(255) NOT NULL COMMENT 'TS代码',
  `trade_date` date NOT NULL COMMENT '交易日期',
  `open` float,
  `high` float,
  `low` float,
  `close` float,
  `pre_close` float COMMENT '昨收价',
  `change` float COMMENT '涨跌额',
  `pct_chg` float COMMENT '涨跌幅',
  `vol` float COMMENT '成交量',
  `amount` float COMMENT '成交额',
  `turnover_rate` float COMMENT '换手率',
  `turnover_rate_f` float COMMENT '换手率(自由流通股)',
  `volume_ratio` float COMMENT '量比',
  `pe` float COMMENT '市盈率（总市值/净利润）',
  `pe_ttm` float COMMENT '市盈率（TTM）',
  `pb` float COMMENT '市净率（总市值/净资产）',
  `ps` float COMMENT '市销率',
  `ps_ttm` float COMMENT '市销率（TTM）',
  `dv_ratio` float COMMENT '股息率（%）',
  `dv_ttm` float COMMENT '股息率（TTM)（%）',
  `total_share` float COMMENT '总股本',
  `float_share` float COMMENT '流通股本',
  `free_share` float COMMENT '自由流通股本',
  `total_mv` float COMMENT '总市值',
  `circ_mv` float COMMENT '流通市值'
);

CREATE TABLE `us_daily_candles` (
  `id` integer PRIMARY KEY AUTO_INCREMENT,
  `ts_code` varchar(255) NOT NULL COMMENT 'TS代码',
  `trade_date` date NOT NULL COMMENT '交易日期',
  `open` float,
  `high` float,
  `low` float,
  `close` float,
  `pre_close` float COMMENT '昨收价',
  `change` float COMMENT '涨跌额',
  `pct_chg` float COMMENT '涨跌幅',
  `vol` float COMMENT '成交量',
  `amount` float COMMENT '成交额',
  `turnover_rate` float COMMENT '换手率',
  `turnover_rate_f` float COMMENT '换手率(自由流通股)',
  `volume_ratio` float COMMENT '量比',
  `pe` float COMMENT '市盈率（总市值/净利润）',
  `pe_ttm` float COMMENT '市盈率（TTM）',
  `pb` float COMMENT '市净率（总市值/净资产）',
  `ps` float COMMENT '市销率',
  `ps_ttm` float COMMENT '市销率（TTM）',
  `dv_ratio` float COMMENT '股息率（%）',
  `dv_ttm` float COMMENT '股息率（TTM)（%）',
  `total_share` float COMMENT '总股本',
  `float_share` float COMMENT '流通股本',
  `free_share` float COMMENT '自由流通股本',
  `total_mv` float COMMENT '总市值',
  `circ_mv` float COMMENT '流通市值'
);

CREATE TABLE `daily_indicators` (
  `id` integer PRIMARY KEY AUTO_INCREMENT,
  `ts_code` varchar(255) NOT NULL COMMENT 'TS代码',
  `trade_date` date NOT NULL COMMENT '交易日期',
  `ma5` float,
  `ma10` float,
  `ma20` float,
  `ma30` float,
  `ma34` float,
  `ma55` float,
  `ma60` float,
  `ma120` float,
  `ma144` float,
  `ma169` float,
  `ema5` float,
  `ema10` float,
  `ema20` float,
  `ema30` float,
  `ema34` float,
  `ema55` float,
  `ema60` float,
  `ema120` float,
  `ema144` float,
  `ema169` float,
  `ma5_slope` float,
  `ma10_slope` float,
  `ma20_slope` float,
  `ma30_slope` float,
  `ma34_slope` float,
  `ma55_slope` float,
  `ma60_slope` float,
  `ma120_slope` float,
  `ma144_slope` float,
  `ma169_slope` float,
  `ema5_slope` float,
  `ema10_slope` float,
  `ema20_slope` float,
  `ema30_slope` float,
  `ema34_slope` float,
  `ema55_slope` float,
  `ema60_slope` float,
  `ema120_slope` float,
  `ema144_slope` float,
  `ema169_slope` float,
  `diff` float,
  `dea` float,
  `macd` float,
  `bias6` float,
  `bias12` float,
  `bias24` float,
  `bias60` float,
  `bias72` float,
  `bias120` float,
  `high_td` tinyint(2),
  `low_td` tinyint(2)
);

CREATE TABLE `daily_long_signals` (
  `id` integer PRIMARY KEY AUTO_INCREMENT,
  `ts_code` varchar(255) NOT NULL COMMENT 'TS代码',
  `trade_date` date NOT NULL COMMENT '交易日期',
  `ma20_up` tinyint(2) COMMENT 'MA20上行',
  `ema20_up` tinyint(2) COMMENT 'EMA20上行',
  `ma30_up` tinyint(2) COMMENT 'MA30上行',
  `ema30_up` tinyint(2) COMMENT 'EMA30上行',
  `ma60_up` tinyint(2) COMMENT 'MA60上行',
  `ema60_up` tinyint(2) COMMENT 'EMA60上行',
  `ma120_up` tinyint(2) COMMENT 'MA120上行',
  `ema120_up` tinyint(2) COMMENT 'EMA120上行',
  `ma_arrange` tinyint(2) COMMENT 'MA多头排列（5/10/20/60）',
  `ema_arrange` tinyint(2) COMMENT 'EMA多头排列（5/10/20/60）',
  `short_ma_arrange1` tinyint(2) COMMENT 'MA短期组合多头排列（5/10/20）',
  `short_ma_arrange2` tinyint(2) COMMENT 'MA短期组合多头排列（5/10/30）',
  `short_ema_arrange1` tinyint(2) COMMENT 'EMA短期组合多头排列（5/10/20）',
  `short_ema_arrange2` tinyint(2) COMMENT 'EMA短期组合多头排列（5/10/30）',
  `middle_ma_arrange1` tinyint(2) COMMENT 'MA中期组合多头排列（10/20/60）',
  `middle_ma_arrange2` tinyint(2) COMMENT 'MA中期组合多头排列（10/20/55）',
  `middle_ema_arrange1` tinyint(2) COMMENT 'EMA中期组合多头排列（10/20/60）',
  `middle_ema_arrange2` tinyint(2) COMMENT 'EMA中期组合多头排列（10/20/55）',
  `long_ma_arrange1` tinyint(2) COMMENT 'MA长期组合多头排列（20/55/120）',
  `long_ma_arrange2` tinyint(2) COMMENT 'MA长期组合多头排列（30/60/120）',
  `long_ema_arrange1` tinyint(2) COMMENT 'EMA长期组合多头排列（20/55/120）',
  `long_ema_arrange2` tinyint(2) COMMENT 'EMA长期组合多头排列（30/60/120）',
  `ma_gold_cross1` tinyint(2) COMMENT 'MA黄金交叉（5/10）',
  `ma_gold_cross2` tinyint(2) COMMENT 'MA黄金交叉（5/20）',
  `ma_gold_cross3` tinyint(2) COMMENT 'MA黄金交叉（10/20）',
  `ma_gold_cross4` tinyint(2) COMMENT 'MA黄金交叉（10/30）',
  `ema_gold_cross1` tinyint(2) COMMENT 'EMA黄金交叉（5/10）',
  `ema_gold_cross2` tinyint(2) COMMENT 'EMA黄金交叉（5/20）',
  `ema_gold_cross3` tinyint(2) COMMENT 'EMA黄金交叉（10/20）',
  `ema_gold_cross4` tinyint(2) COMMENT 'EMA黄金交叉（10/30）',
  `ma_silver_valley` tinyint(2) COMMENT 'MA银山谷（5/10，5/20，10/20）',
  `ema_silver_valley` tinyint(2) COMMENT 'EMA银山谷（5/10，5/20，10/20）',
  `ma_gold_valley` tinyint(2) COMMENT 'MA金山谷（5/10，5/20，10/20）',
  `ema_gold_valley` tinyint(2) COMMENT 'EMA金山谷(5/10,5/20,10/20)',
  `ma_out_sea` tinyint(2) COMMENT 'MA蛟龙出海(5/10/20)',
  `ema_out_sea` tinyint(2) COMMENT 'EMA蛟龙出海(5/10/20)',
  `ma_hold_moon` tinyint(2) COMMENT 'MA烘云托月(5/10/20)',
  `ema_hold_moon` tinyint(2) COMMENT 'EMA烘云托月(5/10/20)',
  `ma_over_gate` tinyint(2) COMMENT 'MA鱼跃龙门(5/10/20)',
  `ema_over_gate` tinyint(2) COMMENT 'EMA鱼跃龙门(5/10/20)',
  `ma_up_ground` tinyint(2) COMMENT 'MA旱地拔葱(5/10/20)',
  `ema_up_ground` tinyint(2) COMMENT 'EMA旱地拔葱(5/10/20)',
  `ma_spider` tinyint(2) COMMENT 'MA金蜘蛛(5/10/20)',
  `ma_spider2` tinyint(2) COMMENT 'MA金蜘蛛(5/10/20/30)',
  `ema_spider` tinyint(2) COMMENT 'EMA金蜘蛛(5/10/20)',
  `ema_spider2` tinyint(2) COMMENT 'EMA金蜘蛛(5/10/20/30)',
  `td8` tinyint(2),
  `td9` tinyint(2),
  `bias6` tinyint(2),
  `bias12` tinyint(2),
  `bias24` tinyint(2),
  `bias60` tinyint(2),
  `bias72` tinyint(2),
  `bias120` tinyint(2),
  `ma60_support` tinyint(2),
  `ema60_support` tinyint(2),
  `ma120_support` tinyint(2),
  `ema120_support` tinyint(2),
  `yearly_price_position` tinyint(5),
  `yearly_price_position10` tinyint(5),
  `yearly_price_position20` tinyint(5),
  `yearly_price_position30` tinyint(5),
  `yearly_price_position50` tinyint(5),
  `yearly_price_position70` tinyint(5),
  `ma_group_glue` tinyint(1),
  `ema_group_glue` tinyint(1),
  `ma_up_arrange51020` tinyint(1),
  `ma_up_arrange5102030` tinyint(1),
  `ma_up_arrange510203060` tinyint(1),
  `ma_up_arrange203060` tinyint(1),
  `ma_up_arrange2060120` tinyint(1),
  `ema_up_arrange51020` tinyint(1),
  `ema_up_arrange5102030` tinyint(1),
  `ema_up_arrange510203060` tinyint(1),
  `ema_up_arrange203060` tinyint(1),
  `ema_up_arrange2055120` tinyint(1),
  `stand_up_ma60` tinyint(1),
  `stand_up_ema60` tinyint(1),
  `stand_up_ma120` tinyint(1),
  `stand_up_ema120` tinyint(1),
  `hammer` tinyint(1),
  `pour_hammer` tinyint(1),
  `short_end` tinyint(1),
  `swallow_up` tinyint(1),
  `attack_short` tinyint(1),
  `first_light` tinyint(1),
  `sunrise` tinyint(1),
  `flat_base` tinyint(1)
);

CREATE TABLE `daily_short_signals` (
  `id` integer PRIMARY KEY AUTO_INCREMENT,
  `ts_code` varchar(255) NOT NULL COMMENT 'TS代码',
  `trade_date` date NOT NULL COMMENT '交易日期',
  `ma20_down` tinyint(2) COMMENT 'MA20下行',
  `ema20_down` tinyint(2) COMMENT 'EMA20下行',
  `ma30_down` tinyint(2) COMMENT 'MA30下行',
  `ema30_down` tinyint(2) COMMENT 'EMA30下行',
  `ma60_down` tinyint(2) COMMENT 'MA60下行',
  `ema60_down` tinyint(2) COMMENT 'EMA60下行',
  `ma120_down` tinyint(2) COMMENT 'MA120下行',
  `ema120_down` tinyint(2) COMMENT 'EMA120下行',
  `ma_arrange` tinyint(2) COMMENT 'MA空头排列（5/10/20/60）',
  `ema_arrange` tinyint(2) COMMENT 'EMA空头排列（5/10/20/60）',
  `short_ma_arrange1` tinyint(2) COMMENT 'MA短期组合空头排列（5/10/20）',
  `short_ma_arrange2` tinyint(2) COMMENT 'MA短期组合空头排列（5/10/30）',
  `short_ema_arrange1` tinyint(2) COMMENT 'EMA短期组合空头排列（5/10/20）',
  `short_ema_arrange2` tinyint(2) COMMENT 'EMA短期组合空头排列（5/10/30）',
  `middle_ma_arrange1` tinyint(2) COMMENT 'MA中期组合空头排列（10/20/60）',
  `middle_ma_arrange2` tinyint(2) COMMENT 'MA中期组合空头排列（10/20/55）',
  `middle_ema_arrange1` tinyint(2) COMMENT 'EMA中期组合空头排列（10/20/60）',
  `middle_ema_arrange2` tinyint(2) COMMENT 'EMA中期组合空头排列（10/20/55）',
  `long_ma_arrange1` tinyint(2) COMMENT 'MA长期组合空头排列（20/55/120）',
  `long_ma_arrange2` tinyint(2) COMMENT 'MA长期组合空头排列（30/60/120）',
  `long_ema_arrange1` tinyint(2) COMMENT 'EMA长期组合空头排列（20/55/120）',
  `long_ema_arrange2` tinyint(2) COMMENT 'EMA长期组合空头排列（30/60/120）',
  `ma_dead_cross_1` tinyint(2) COMMENT 'MA死亡交叉（5/10）',
  `ma_dead_cross2` tinyint(2) COMMENT 'MA死亡交叉（5/20）',
  `ma_dead_cross3` tinyint(2) COMMENT 'MA死亡交叉（10/20）',
  `ma_dead_cross4` tinyint(2) COMMENT 'MA死亡交叉（10/30）',
  `ema_dead_cross1` tinyint(2) COMMENT 'EMA死亡交叉（5/10）',
  `ema_dead_cross2` tinyint(2) COMMENT 'EMA死亡交叉（5/20）',
  `ema_dead_cross3` tinyint(2) COMMENT 'EMA死亡交叉（10/20）',
  `ema_dead_cross4` tinyint(2) COMMENT 'EMA死亡交叉（10/30）',
  `ma_dead_valley` tinyint(2) COMMENT 'MA死亡谷（5/10，5/20，10/20）',
  `ema_dead_valley` tinyint(2) COMMENT 'EMA死亡谷（5/10，5/20，10/20）',
  `ma_knife` tinyint(2) COMMENT 'MA断头铡刀(5/10/20)',
  `ema_knife` tinyint(2) COMMENT 'EMA断头铡刀(5/10/20)',
  `ma_dark_cloud` tinyint(2) COMMENT 'MA乌云密布(5/10/20)',
  `ema_dark_cloud` tinyint(2) COMMENT 'EMA乌云密布(5/10/20)',
  `ma_set_sail` tinyint(2) COMMENT 'MA战机起航(5/10/20)',
  `ema_set_sail` tinyint(2) COMMENT 'EMA战机起航(5/10/20)',
  `ma_supreme` tinyint(2) COMMENT 'MA气贯长虹(5/10/20)',
  `ema_supreme` tinyint(2) COMMENT 'EMA气贯长虹(5/10/20)',
  `ma_dead_jump` tinyint(2) COMMENT 'MA绝命跳(5/10/20)',
  `ema_dead_jump` tinyint(2) COMMENT 'EMA绝命跳(5/10/20)',
  `ma_spider` tinyint(2) COMMENT 'MA毒蜘蛛(5/10/20)',
  `ma_spider2` tinyint(2) COMMENT 'MA毒蜘蛛(5/10/20/30)',
  `ema_spider` tinyint(2) COMMENT 'EMA毒蜘蛛(5/10/20)',
  `ema_spider2` tinyint(2) COMMENT 'EMA毒蜘蛛(5/10/20/30)',
  `td8` tinyint(2),
  `td9` tinyint(2),
  `bias6` tinyint(2),
  `bias12` tinyint(2),
  `bias24` tinyint(2),
  `bias60` tinyint(2),
  `bias72` tinyint(2),
  `bias120` tinyint(2)
);

CREATE TABLE `stock_long_signals` (
  `id` integer PRIMARY KEY AUTO_INCREMENT,
  `ts_code` varchar(255) NOT NULL COMMENT 'TS代码',
  `ma20_up` tinyint(2) COMMENT 'MA20上行',
  `ema20_up` tinyint(2) COMMENT 'EMA20上行',
  `ma30_up` tinyint(2) COMMENT 'MA30上行',
  `ema30_up` tinyint(2) COMMENT 'EMA30上行',
  `ma60_up` tinyint(2) COMMENT 'MA60上行',
  `ema60_up` tinyint(2) COMMENT 'EMA60上行',
  `ma120_up` tinyint(2) COMMENT 'MA120上行',
  `ema120_up` tinyint(2) COMMENT 'EMA120上行',
  `ma_arrange` tinyint(2) COMMENT 'MA多头排列（5/10/20/60）',
  `ema_arrange` tinyint(2) COMMENT 'EMA多头排列（5/10/20/60）',
  `short_ma_arrange1` tinyint(2) COMMENT 'MA短期组合多头排列（5/10/20）',
  `short_ma_arrange2` tinyint(2) COMMENT 'MA短期组合多头排列（5/10/30）',
  `short_ema_arrange1` tinyint(2) COMMENT 'EMA短期组合多头排列（5/10/20）',
  `short_ema_arrange2` tinyint(2) COMMENT 'EMA短期组合多头排列（5/10/30）',
  `middle_ma_arrange1` tinyint(2) COMMENT 'MA中期组合多头排列（10/20/60）',
  `middle_ma_arrange2` tinyint(2) COMMENT 'MA中期组合多头排列（10/20/55）',
  `middle_ema_arrange1` tinyint(2) COMMENT 'EMA中期组合多头排列（10/20/60）',
  `middle_ema_arrange2` tinyint(2) COMMENT 'EMA中期组合多头排列（10/20/55）',
  `long_ma_arrange1` tinyint(2) COMMENT 'MA长期组合多头排列（20/55/120）',
  `long_ma_arrange2` tinyint(2) COMMENT 'MA长期组合多头排列（30/60/120）',
  `long_ema_arrange1` tinyint(2) COMMENT 'EMA长期组合多头排列（20/55/120）',
  `long_ema_arrange2` tinyint(2) COMMENT 'EMA长期组合多头排列（30/60/120）',
  `ma_gold_cross1` tinyint(2) COMMENT 'MA黄金交叉（5/10）',
  `ma_gold_cross2` tinyint(2) COMMENT 'MA黄金交叉（5/20）',
  `ma_gold_cross3` tinyint(2) COMMENT 'MA黄金交叉（10/20）',
  `ma_gold_cross4` tinyint(2) COMMENT 'MA黄金交叉（10/30）',
  `ema_gold_cross1` tinyint(2) COMMENT 'EMA黄金交叉（5/10）',
  `ema_gold_cross2` tinyint(2) COMMENT 'EMA黄金交叉（5/20）',
  `ema_gold_cross3` tinyint(2) COMMENT 'EMA黄金交叉（10/20）',
  `ema_gold_cross4` tinyint(2) COMMENT 'EMA黄金交叉（10/30）',
  `ma_silver_valley` tinyint(2) COMMENT 'MA银山谷（5/10，5/20，10/20）',
  `ema_silver_valley` tinyint(2) COMMENT 'EMA银山谷（5/10，5/20，10/20）',
  `ma_gold_valley` tinyint(2) COMMENT 'MA金山谷（5/10，5/20，10/20）',
  `ema_gold_valley` tinyint(2) COMMENT 'EMA金山谷(5/10,5/20,10/20)',
  `ma_out_sea` tinyint(2) COMMENT 'MA蛟龙出海(5/10/20)',
  `ema_out_sea` tinyint(2) COMMENT 'EMA蛟龙出海(5/10/20)',
  `ma_hold_moon` tinyint(2) COMMENT 'MA烘云托月(5/10/20)',
  `ema_hold_moon` tinyint(2) COMMENT 'EMA烘云托月(5/10/20)',
  `ma_over_gate` tinyint(2) COMMENT 'MA鱼跃龙门(5/10/20)',
  `ema_over_gate` tinyint(2) COMMENT 'EMA鱼跃龙门(5/10/20)',
  `ma_up_ground` tinyint(2) COMMENT 'MA旱地拔葱(5/10/20)',
  `ema_up_ground` tinyint(2) COMMENT 'EMA旱地拔葱(5/10/20)',
  `ma_spider` tinyint(2) COMMENT 'MA金蜘蛛(5/10/20)',
  `ma_spider2` tinyint(2) COMMENT 'MA金蜘蛛(5/10/20/30)',
  `ema_spider` tinyint(2) COMMENT 'EMA金蜘蛛(5/10/20)',
  `ema_spider2` tinyint(2) COMMENT 'EMA金蜘蛛(5/10/20/30)',
  `td8` tinyint(2),
  `td9` tinyint(2),
  `bias6` tinyint(2),
  `bias12` tinyint(2),
  `bias24` tinyint(2),
  `bias60` tinyint(2),
  `bias72` tinyint(2),
  `bias120` tinyint(2),
  `ma60_support` tinyint(2),
  `ema60_support` tinyint(2),
  `ma120_support` tinyint(2),
  `ema120_support` tinyint(2),
  `yearly_price_position` tinyint(5),
  `yearly_price_position10` tinyint(5),
  `yearly_price_position20` tinyint(5),
  `yearly_price_position30` tinyint(5),
  `yearly_price_position50` tinyint(5),
  `yearly_price_position70` tinyint(5),
  `ma_group_glue` tinyint(1),
  `ema_group_glue` tinyint(1),
  `ma_up_arrange51020` tinyint(1),
  `ma_up_arrange5102030` tinyint(1),
  `ma_up_arrange510203060` tinyint(1),
  `ma_up_arrange203060` tinyint(1),
  `ma_up_arrange2060120` tinyint(1),
  `ema_up_arrange51020` tinyint(1),
  `ema_up_arrange5102030` tinyint(1),
  `ema_up_arrange510203060` tinyint(1),
  `ema_up_arrange203060` tinyint(1),
  `ema_up_arrange2055120` tinyint(1),
  `stand_up_ma60` tinyint(1),
  `stand_up_ema60` tinyint(1),
  `stand_up_ma120` tinyint(1),
  `stand_up_ema120` tinyint(1),
  `hammer` tinyint(1),
  `pour_hammer` tinyint(1),
  `short_end` tinyint(1),
  `swallow_up` tinyint(1),
  `attack_short` tinyint(1),
  `first_light` tinyint(1),
  `sunrise` tinyint(1),
  `flat_base` tinyint(1)
);

CREATE TABLE `stock_short_signals` (
  `id` integer PRIMARY KEY AUTO_INCREMENT,
  `ts_code` varchar(255) NOT NULL COMMENT 'TS代码',
  `ma20_down` tinyint(2) COMMENT 'MA20下行',
  `ema20_down` tinyint(2) COMMENT 'EMA20下行',
  `ma30_down` tinyint(2) COMMENT 'MA30下行',
  `ema30_down` tinyint(2) COMMENT 'EMA30下行',
  `ma60_down` tinyint(2) COMMENT 'MA60下行',
  `ema60_down` tinyint(2) COMMENT 'EMA60下行',
  `ma120_down` tinyint(2) COMMENT 'MA120下行',
  `ema120_down` tinyint(2) COMMENT 'EMA120下行',
  `ma_arrange` tinyint(2) COMMENT 'MA空头排列（5/10/20/60）',
  `ema_arrange` tinyint(2) COMMENT 'EMA空头排列（5/10/20/60）',
  `short_ma_arrange1` tinyint(2) COMMENT 'MA短期组合空头排列（5/10/20）',
  `short_ma_arrange2` tinyint(2) COMMENT 'MA短期组合空头排列（5/10/30）',
  `short_ema_arrange1` tinyint(2) COMMENT 'EMA短期组合空头排列（5/10/20）',
  `short_ema_arrange2` tinyint(2) COMMENT 'EMA短期组合空头排列（5/10/30）',
  `middle_ma_arrange1` tinyint(2) COMMENT 'MA中期组合空头排列（10/20/60）',
  `middle_ma_arrange2` tinyint(2) COMMENT 'MA中期组合空头排列（10/20/55）',
  `middle_ema_arrange1` tinyint(2) COMMENT 'EMA中期组合空头排列（10/20/60）',
  `middle_ema_arrange2` tinyint(2) COMMENT 'EMA中期组合空头排列（10/20/55）',
  `long_ma_arrange1` tinyint(2) COMMENT 'MA长期组合空头排列（20/55/120）',
  `long_ma_arrange2` tinyint(2) COMMENT 'MA长期组合空头排列（30/60/120）',
  `long_ema_arrange1` tinyint(2) COMMENT 'EMA长期组合空头排列（20/55/120）',
  `long_ema_arrange2` tinyint(2) COMMENT 'EMA长期组合空头排列（30/60/120）',
  `ma_dead_cross1` tinyint(2) COMMENT 'MA死亡交叉（5/10）',
  `ma_dead_cross2` tinyint(2) COMMENT 'MA死亡交叉（5/20）',
  `ma_dead_cross3` tinyint(2) COMMENT 'MA死亡交叉（10/20）',
  `ma_dead_cross4` tinyint(2) COMMENT 'MA死亡交叉（10/30）',
  `ema_dead_cross1` tinyint(2) COMMENT 'EMA死亡交叉（5/10）',
  `ema_dead_cross2` tinyint(2) COMMENT 'EMA死亡交叉（5/20）',
  `ema_dead_cross3` tinyint(2) COMMENT 'EMA死亡交叉（10/20）',
  `ema_dead_cross4` tinyint(2) COMMENT 'EMA死亡交叉（10/30）',
  `ma_dead_valley` tinyint(2) COMMENT 'MA死亡谷（5/10，5/20，10/20）',
  `ema_dead_valley` tinyint(2) COMMENT 'EMA死亡谷（5/10，5/20，10/20）',
  `ma_knife` tinyint(2) COMMENT 'MA断头铡刀(5/10/20)',
  `ema_knife` tinyint(2) COMMENT 'EMA断头铡刀(5/10/20)',
  `ma_dark_cloud` tinyint(2) COMMENT 'MA乌云密布(5/10/20)',
  `ema_dark_cloud` tinyint(2) COMMENT 'EMA乌云密布(5/10/20)',
  `ma_set_sail` tinyint(2) COMMENT 'MA战机起航(5/10/20)',
  `ema_set_sail` tinyint(2) COMMENT 'EMA战机起航(5/10/20)',
  `ma_supreme` tinyint(2) COMMENT 'MA气贯长虹(5/10/20)',
  `ema_supreme` tinyint(2) COMMENT 'EMA气贯长虹(5/10/20)',
  `ma_dead_jump` tinyint(2) COMMENT 'MA绝命跳(5/10/20)',
  `ema_dead_jump` tinyint(2) COMMENT 'EMA绝命跳(5/10/20)',
  `ma_spider` tinyint(2) COMMENT 'MA毒蜘蛛(5/10/20)',
  `ma_spider2` tinyint(2) COMMENT 'MA毒蜘蛛(5/10/20/30)',
  `ema_spider` tinyint(2) COMMENT 'EMA毒蜘蛛(5/10/20)',
  `ema_spider2` tinyint(2) COMMENT 'EMA毒蜘蛛(5/10/20/30)',
  `td_8` tinyint(2),
  `td_9` tinyint(2),
  `bias6` tinyint(2),
  `bias12` tinyint(2),
  `bias24` tinyint(2),
  `bias60` tinyint(2),
  `bias72` tinyint(2),
  `bias120` tinyint(2)
);

CREATE TABLE `weekly_candles` (
  `id` integer PRIMARY KEY AUTO_INCREMENT,
  `ts_code` varchar(255) NOT NULL COMMENT 'TS代码',
  `trade_date` date NOT NULL COMMENT '交易日期',
  `open` float,
  `high` float,
  `low` float,
  `close` float,
  `pre_close` float,
  `change` float,
  `pct_chg` float,
  `vol` float,
  `amount` float,
  `ma5` float,
  `ma10` float,
  `ma20` float,
  `ma30` float,
  `ma60` float,
  `ema5` float,
  `ema10` float,
  `ema20` float,
  `ema30` float,
  `ema60` float,
  `diff` float,
  `dea` float,
  `macd` float
);

CREATE TABLE `weekly_indicators` (
  `id` integer PRIMARY KEY AUTO_INCREMENT,
  `ts_code` varchar(255) NOT NULL COMMENT 'TS代码',
  `trade_date` date NOT NULL COMMENT '交易日期',
  `ma5` float,
  `ma10` float,
  `ma20` float,
  `ma30` float,
  `ma60` float,
  `ema5` float,
  `ema10` float,
  `ema20` float,
  `ema30` float,
  `ema60` float,
  `diff` float,
  `dea` float,
  `macd` float
);

CREATE TABLE `weekly_long_signals` (
  `id` integer PRIMARY KEY AUTO_INCREMENT,
  `ts_code` varchar(255) NOT NULL COMMENT 'TS代码',
  `trade_date` date NOT NULL COMMENT '交易日期',
  `ma20_up` tinyint(2) COMMENT 'MA20上行',
  `ema20_up` tinyint(2) COMMENT 'EMA20上行',
  `ma30_up` tinyint(2) COMMENT 'MA30上行',
  `ema30_up` tinyint(2) COMMENT 'EMA30上行',
  `ma60_up` tinyint(2) COMMENT 'MA60上行',
  `ema60_up` tinyint(2) COMMENT 'EMA60上行',
  `ma_arrange` tinyint(2) COMMENT 'MA多头排列（5/10/20/60）',
  `ema_arrange` tinyint(2) COMMENT 'EMA多头排列（5/10/20/60）',
  `short_ma_arrange1` tinyint(2) COMMENT 'MA短期组合多头排列（5/10/20）',
  `short_ma_arrange2` tinyint(2) COMMENT 'MA短期组合多头排列（5/10/30）',
  `short_ema_arrange1` tinyint(2) COMMENT 'EMA短期组合多头排列（5/10/20）',
  `short_ema_arrange2` tinyint(2) COMMENT 'EMA短期组合多头排列（5/10/30）',
  `middle_ma_arrange1` tinyint(2) COMMENT 'MA中期组合多头排列（10/20/60）',
  `middle_ma_arrange2` tinyint(2) COMMENT 'MA中期组合多头排列（10/20/55）',
  `middle_ema_arrange1` tinyint(2) COMMENT 'EMA中期组合多头排列（10/20/60）',
  `middle_ema_arrange2` tinyint(2) COMMENT 'EMA中期组合多头排列（10/20/55）',
  `ma_gold_cross1` tinyint(2) COMMENT 'MA黄金交叉（5/10）',
  `ma_gold_cross2` tinyint(2) COMMENT 'MA黄金交叉（5/20）',
  `ma_gold_cross3` tinyint(2) COMMENT 'MA黄金交叉（10/20）',
  `ma_gold_cross4` tinyint(2) COMMENT 'MA黄金交叉（10/30）',
  `ema_gold_cross1` tinyint(2) COMMENT 'EMA黄金交叉（5/10）',
  `ema_gold_cross2` tinyint(2) COMMENT 'EMA黄金交叉（5/20）',
  `ema_gold_cross3` tinyint(2) COMMENT 'EMA黄金交叉（10/20）',
  `ema_gold_cross4` tinyint(2) COMMENT 'EMA黄金交叉（10/30）',
  `ma_out_sea` tinyint(2) COMMENT 'MA蛟龙出海(5/10/20)',
  `ema_out_sea` tinyint(2) COMMENT 'EMA蛟龙出海(5/10/20)',
  `ma_hold_moon` tinyint(2) COMMENT 'MA烘云托月(5/10/20)',
  `ema_hold_moon` tinyint(2) COMMENT 'EMA烘云托月(5/10/20)',
  `ma_over_gate` tinyint(2) COMMENT 'MA鱼跃龙门(5/10/20)',
  `ema_over_gate` tinyint(2) COMMENT 'EMA鱼跃龙门(5/10/20)',
  `ma_up_group` tinyint(2) COMMENT 'MA旱地拔葱(5/10/20)',
  `ema_up_group` tinyint(2) COMMENT 'EMA旱地拔葱(5/10/20)',
  `ma_group_glue` tinyint(1),
  `ema_group_glue` tinyint(1),
  `ma_up_arrange51020` tinyint(1),
  `ma_up_arrange5102030` tinyint(1),
  `ma_up_arrange510203060` tinyint(1),
  `ema_up_arrange51020` tinyint(1),
  `ema_up_arrange5102030` tinyint(1),
  `ema_up_arrange510203060` tinyint(1)
);

CREATE INDEX `weekly_long_signals_index_ts_code` ON `weekly_long_signals` (`ts_code`);

CREATE INDEX `weekly_long_signals_index_trade_date` ON `weekly_long_signals` (`trade_date`);

CREATE UNIQUE INDEX `weekly_long_signals_unique` ON `weekly_long_signals` (`ts_code`, `trade_date`);

CREATE TABLE `users` (
  `id` integer PRIMARY KEY AUTO_INCREMENT,
  `username` varchar(255),
  `nickname` varchar(255),
  `email` varchar(255),
  `password` varchar(255)
);

CREATE TABLE `invite_codes` (
  `id` integer PRIMARY KEY AUTO_INCREMENT,
  `code` varchar(255),
  `user_id` integer
);

CREATE TABLE `user_stock_positions` (
  `id` integer PRIMARY KEY AUTO_INCREMENT,
  `user_id` integer
);

CREATE UNIQUE INDEX `trade_calendar_unique` ON `trade_calendar` (`exchange`, `cal_date`);

CREATE INDEX `stocks_index_exchange` ON `stocks` (`exchange`);

CREATE INDEX `stocks_index_ts_code` ON `stocks` (`ts_code`);

CREATE INDEX `cn_daily_candles_index_ts_code` ON `cn_daily_candles` (`ts_code`);

CREATE INDEX `cn_daily_candles_index_trade_date` ON `cn_daily_candles` (`trade_date`);

CREATE UNIQUE INDEX `cn_daily_candles_unique` ON `cn_daily_candles` (`ts_code`, `trade_date`);

CREATE INDEX `hk_daily_candles_index_ts_code` ON `hk_daily_candles` (`ts_code`);

CREATE INDEX `hk_daily_candles_index_trade_date` ON `hk_daily_candles` (`trade_date`);

CREATE UNIQUE INDEX `hk_daily_candles_unique` ON `hk_daily_candles` (`ts_code`, `trade_date`);

CREATE INDEX `us_daily_candles_index_ts_code` ON `us_daily_candles` (`ts_code`);

CREATE INDEX `us_daily_candles_index_trade_date` ON `us_daily_candles` (`trade_date`);

CREATE UNIQUE INDEX `us_daily_candles_unique` ON `us_daily_candles` (`ts_code`, `trade_date`);

CREATE INDEX `daily_indicators_index_ts_code` ON `daily_indicators` (`ts_code`);

CREATE INDEX `daily_indicators_index_trade_date` ON `daily_indicators` (`trade_date`);

CREATE UNIQUE INDEX `daily_indicators_unique` ON `daily_indicators` (`ts_code`, `trade_date`);

CREATE INDEX `daily_long_signals_index_ts_code` ON `daily_long_signals` (`ts_code`);

CREATE INDEX `daily_long_signals_index_trade_date` ON `daily_long_signals` (`trade_date`);

CREATE UNIQUE INDEX `daily_long_signals_unique` ON `daily_long_signals` (`ts_code`, `trade_date`);

CREATE INDEX `daily_short_signals_index_ts_code` ON `daily_short_signals` (`ts_code`);

CREATE INDEX `daily_short_signals_index_trade_date` ON `daily_short_signals` (`trade_date`);

CREATE UNIQUE INDEX `daily_short_signals_unique` ON `daily_short_signals` (`ts_code`, `trade_date`);

CREATE INDEX `stock_long_signals_index_ts_code` ON `stock_long_signals` (`ts_code`);

CREATE INDEX `stock_short_signals_index_ts_code` ON `stock_short_signals` (`ts_code`);

CREATE INDEX `weekly_candles_index_23` ON `weekly_candles` (`ts_code`);

CREATE INDEX `weekly_candles_index_24` ON `weekly_candles` (`trade_date`);

CREATE UNIQUE INDEX `weekly_candle_unique` ON `weekly_candles` (`ts_code`, `trade_date`);

CREATE INDEX `weekly_indicators_index_ts_code` ON `weekly_indicators` (`ts_code`);

CREATE INDEX `weekly_indicators_index_trade_date` ON `weekly_indicators` (`trade_date`);

CREATE UNIQUE INDEX `weekly_indicators_unique` ON `weekly_indicators` (`ts_code`, `trade_date`);