CREATE TABLE `trade_calendar` (
  `id` integer PRIMARY KEY AUTO_INCREMENT,
  `exchange` varchar(255) NOT NULL COMMENT '交易所 SSE上交所 SZSE深交所 HK 港交所 US 美交所',
  `cal_date` date NOT NULL COMMENT '日历日期',
  `is_open` tinyint NOT NULL COMMENT '是否交易 0休市 1交易',
  `pretrade_date` date COMMENT '上一个交易日',
  `candle_ready` tinyint NOT NULL DEFAULT 0 COMMENT '日K是否获取完成 0否 1是',
  `basic_ready` tinyint NOT NULL DEFAULT 0 COMMENT '每日指标是获取完成 0否 1是',
);

CREATE TABLE `stocks` (
  `id` integer PRIMARY KEY AUTO_INCREMENT,
  `ts_code` varchar(255) UNIQUE NOT NULL COMMENT 'TS代码',
  `symbol` varchar(255) COMMENT '股票代码',
  `name` varchar(255) COMMENT '股票名称',
  `area` varchar(255) COMMENT '地域',
  `industry` varchar(255) COMMENT '所属行业',
  `fullname` varchar(255) COMMENT '股票全称',
  `enname` varchar(255) COMMENT '英文全称',
  `cnspell` varchar(255) COMMENT '拼音缩写',
  `market` varchar(255) COMMENT '市场类型',
  `exchange` varchar(255) NOT NULL COMMENT '交易所代码 SSE SZSE HK US',
  `list_status` varchar(255) COMMENT '上市状态 L上市 D退市 P暂停上市',
  `list_date` varchar(255) COMMENT '上市日期',
  `delist_date` varchar(255) COMMENT '退市日期',
  `is_hs` varchar(255) COMMENT '是否沪深港通标的，N否 H沪股通 S深股通',
  `turnover_rate` float COMMENT '换手率',
  `turnover_rate_f` float COMMENT '换手率(自由流通股)',
  `volume_ratio` float COMMENT '量比',
  `pe` float COMMENT '市盈率（总市值/净利润）',
  `pe_ttm` float COMMENT '市盈率（TTM）',
  `pb` float COMMENT '市净率（总市值/净资产）',
  `ps` float COMMENT '市销率',
  `ps_ttm` float COMMENT '市销率（TTM）',
  `dv_ratio` float COMMENT '股息率（%）',
  `dv_ttm` float COMMENT '股息率（TTM)（%）',
  `total_share` float COMMENT '总股本',
  `float_share` float COMMENT '流通股本',
  `free_share` float COMMENT '自由流通股本',
  `total_mv` float COMMENT '总市值',
  `circ_mv` float COMMENT '流通市值'
);

CREATE TABLE `daily_candles` (
  `id` integer PRIMARY KEY AUTO_INCREMENT,
  `ts_code` varchar(255) NOT NULL COMMENT 'TS代码',
  `trade_date` date NOT NULL COMMENT '交易日期',
  `open` float,
  `high` float,
  `low` float,
  `close` float,
  `pre_close` float COMMENT '昨收价',
  `change` float COMMENT '涨跌额',
  `pct_chg` float COMMENT '涨跌幅',
  `vol` float COMMENT '成交量',
  `amount` float COMMENT '成交额',
  `turnover_rate` float COMMENT '换手率',
  `turnover_rate_f` float COMMENT '换手率(自由流通股)',
  `volume_ratio` float COMMENT '量比',
  `pe` float COMMENT '市盈率（总市值/净利润）',
  `pe_ttm` float COMMENT '市盈率（TTM）',
  `pb` float COMMENT '市净率（总市值/净资产）',
  `ps` float COMMENT '市销率',
  `ps_ttm` float COMMENT '市销率（TTM）',
  `dv_ratio` float COMMENT '股息率（%）',
  `dv_ttm` float COMMENT '股息率（TTM)（%）',
  `total_share` float COMMENT '总股本',
  `float_share` float COMMENT '流通股本',
  `free_share` float COMMENT '自由流通股本',
  `total_mv` float COMMENT '总市值',
  `circ_mv` float COMMENT '流通市值',
  `ma5` float,
  `ma10` float,
  `ma20` float,
  `ma30` float,
  `ma34` float,
  `ma55` float,
  `ma60` float,
  `ma120` float,
  `ma144` float,
  `ma169` float,
  `ema5` float,
  `ema10` float,
  `ema20` float,
  `ema30` float,
  `ema34` float,
  `ema55` float,
  `ema60` float,
  `ema120` float,
  `ema144` float,
  `ema169` float,
  `ma5_slope` float,
  `ma10_slope` float,
  `ma20_slope` float,
  `ma30_slope` float,
  `ma34_slope` float,
  `ma55_slope` float,
  `ma60_slope` float,
  `ma120_slope` float,
  `ma144_slope` float,
  `ma169_slope` float,
  `ema5_slope` float,
  `ema10_slope` float,
  `ema20_slope` float,
  `ema30_slope` float,
  `ema34_slope` float,
  `ema55_slope` float,
  `ema60_slope` float,
  `ema120_slope` float,
  `ema144_slope` float,
  `ema169_slope` float,
  `diff` float,
  `dea` float,
  `macd` float,
  `bias6` float,
  `bias12` float,
  `bias24` float,
  `bias60` float
);

CREATE TABLE `weekly_candles` (
  `id` integer PRIMARY KEY AUTO_INCREMENT,
  `ts_code` varchar(255) NOT NULL COMMENT 'TS代码',
  `trade_date` date NOT NULL COMMENT '交易日期',
  `open` float,
  `high` float,
  `low` float,
  `close` float,
  `pre_close` float,
  `change` float,
  `pct_chg` float,
  `vol` float,
  `amount` float,
  `ma5` float,
  `ma10` float,
  `ma20` float,
  `ma30` float,
  `ma60` float,
  `ma120` float,
  `diff` float,
  `dea` float,
  `macd` float,
  `bias6` float,
  `bias12` float,
  `bias24` float
);

CREATE UNIQUE INDEX `trade_calendar_unique` ON `trade_calendar` (`exchange`, `cal_date`);

CREATE INDEX `stocks_index_1` ON `stocks` (`exchange`);

CREATE INDEX `stocks_index_2` ON `stocks` (`ts_code`);

CREATE INDEX `daily_candles_index_3` ON `daily_candles` (`ts_code`);

CREATE UNIQUE INDEX `daily_candle_unique` ON `daily_candles` (`ts_code`, `trade_date`);

CREATE UNIQUE INDEX `weekly_candle_unique` ON `weekly_candles` (`ts_code`, `trade_date`);
