name: CN history daily candle

on: workflow_dispatch

jobs:
  build:

    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        brew install ta-lib
    - name: get CN history daily candle
      run: |
        python jobs/history/cn_stock_daily.py