name: CN history daily candle

on: workflow_dispatch

jobs:
  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        git clone git@github.com:mrjbq7/ta-lib.git
        cd ta-lib
        python setup.py install
    - name: get CN history daily candle
      run: |
        python jobs/history/cn_stock_daily.py
