name: History daily candle CN

on: workflow_dispatch

jobs:
  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip3 install virtualenv
        python3 -m venv .venv
        source .venv/bin/activate
        pip3 install -r requirements.txt
    - name: get CN history daily candle
      run: |
        source .venv/bin/activate
        sudo -s
        echo "include /usr/local/lib" >> /etc/ld.so.conf
        ldconfig
        python jobs/history/cn_stock_daily.py
