name: CN daily candle

on:
#  schedule:
    # * 每天17点，开始获取K线行情数据
#    - cron: '0 17 */1 */1 *'
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        pip3 install virtualenv
        python3 -m venv .venv
        source .venv/bin/activate
        pip3 install -r requirements.txt
    - name: get CN daily candle
      run: |
        source .venv/bin/activate
        sudo -s
        echo "include /usr/local/lib" >> /etc/ld.so.conf
        ldconfig
        python jobs/daily/cn_stock_daily.py
