name: daily candle

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/
    - name: get CN daily candle
      run: |
        python jobs/daily/cn_stock_daily.py
    - name: get HK daily candle
      run: |
        python jobs/daily/hk_stock_daily.py
    - name: get US daily candle
      run: |
        python jobs/daily/us_stock_daily.py
