name: CN daily candle

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: get stock daily candle
      run: |
        python jobs/daily/cn_stock_daily.py
    - name: get stock daily candle
      run: |
        python jobs/daily/hk_stock_daily.py
    - name: get stock daily candle
      run: |
        python jobs/daily/us_stock_daily.py