name: History daily candle HK

on: workflow_dispatch

jobs:
  build:

    runs-on: [self-hosted, no-talib]
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip3 install virtualenv
        python3 -m venv .venv
        source .venv/bin/activate
        pip3 install -r requirements-notalib.txt
    - name: get HK history daily candle
      run: |
        source .venv/bin/activate
        sudo -s
        echo "include /usr/local/lib" >> /etc/ld.so.conf
        ldconfig
        python jobs/history/hk_stock_daily.py