name: Test workflow

on: workflow_dispatch

jobs:
  build:

    runs-on: [self-hosted, talib]
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip3 install virtualenv
        python3 -m venv .venv
        source .venv/bin/activate
        pip3 install -r requirements.txt
    - name: test
      run: |
        source .venv/bin/activate
        sudo -s
        echo "include /usr/local/lib" >> /etc/ld.so.conf
        ldconfig
        python test.py
